----------------------------------------------
-- (french) -- update 11 fev 2007 19h46 (KKram)
----------------------------------------------
if (GetLocale() == "frFR") then

AtlasLoot_LootTypes = { "Instances - Azeroth", "Instances - Kalimdor", "Instances - Outreterre", "Rencontres de Raid", "Objets de Sets", "Factions", "JcJ" };

AtlasLoot_Zones = {
	{ 
		{ "Profondeurs de Rochenoire", "" },
		{ "Pic de Rochenoire inf\195\169rieur", "" },
		{ "Pic de Rochenoire sup\195\169rieur", "" },
		{ "Repaire de l\'Aile noire", "" },
		{ "Les Mortemines", "" },
		{ "Gnomeregan", "" },
		{ "Karazhan", "" },
		{ "C\197\147ur du Magma", "" },
		{ "Naxxramas", "" },
		{ "Monast\195\168re \195\169carlate", "" },
		{ "Scholomance", "" },
		{ "Donjon d\'Ombrecroc", "" },
		{ "La Prison", "" },
		{ "Stratholme", "" },
		{ "Le temple englouti", "" },
		{ "Uldaman", "" },
		{ "Zul'Gurub", "" },
	},
	{
        { "Profondeurs de Brassenoire", "" },
        { "GdT: Les Contreforts d'Hautebrande d'antan", "" },
        { "GdT: Les Morasses Noires", "" },
        { "Hache-Tripes (Est)", "" },
        { "Hache-Tripes (Nord)", "" },
        { "Hache-Tripes (Ouest)", "" },
        { "Maraudon", "" },
        { "Repaire d\'Onyxia", "" },
        { "Gouffre de Ragefeu", "" },
        { "Souilles de Tranchebauge", "" },
        { "Kraal de Tranchebauge", "" },
        { "Ruines d'Ahn'Qiraj", "" },
        { "Le temple d\'Ahn\'Qiraj", "" },
        { "Cavernes des lamentations", "" },
        { "Zul'Farrak", "" },
    },
    {
        { "Auch: Tombe-Mana", "" },
        { "Auch: Cryptes Auchenaï", "" },
        { "Auch: Salles des Sethekk", "" },
        { "Auch: Le Labyrinthe des Ombres", "" },
        { "RdG: Les Enclos aux Esclaves", "" },
        { "RdG: La Basse Tourbi\195\168re", "" },
        { "RdG: Le Caveau de la Vapeur", "" },
		{ "RdG: Sanctuaire du Serpent", "" },
	    { "Repaire de Gruul", "" },
        { "CFI: Remparts des Flammes infernales", "" },
        { "CFI: La Fournaise du sang", "" },
        { "CFI: Les Salles bris\195\169es", "" },
        { "DT: L'Arcatraz", "" },
        { "DT: La Botanica", "" },
        { "DT: Le Mechanar", "" },
    },
    {
        { "Azuregos", "AAzuregos" },
		{ "Seigneur funeste Kazzak", "DoomLordKazzak"},
		{ "Marche-funeste", "DDoomwalker" },
        { "Emeriss", "DEmeriss" },
		{ "G\195\169n\195\169ralissime Kruul", "KKruul" },
        { "Lethon", "DLethon"},
        { "Taerar", "DTaerar" },
        { "Ysondre", "DYsondre" },
    },
    {
        { "Set Ar\195\168nes JcJ", "" },
        { "R\195\169compenses mode h\195\169ro\195\175que - Acc\195\169ssoires et Armes", "HardModeToken" },
        { "R\195\169compenses mode h\195\169ro\195\175que - Mat\195\169riels de R\195\169sistance au Feu", "HardModeToken2" },
        { "Objets l\195\169gendaires", "Legendaries" },
		{ "Montures rares", "RareMounts" },
		{ "Tabards", "Tabards" },
        { "Sets JcJ (Niveau 60)", "" },
        { "Sets JCJ (Niveau 70)", "" },
        { "Sets des Ruines d'Ahn'Qiraj", "" },
        { "Sets du Temple d'Ahn'Qiraj", "" },
        { "Sets Donjon 1/2", "" },
        { "Sets Donjon 3", "" },
        { "Sets T1", "" },
        { "Sets T2", "" },
        { "Sets T3", "" },
        { "Sets T4", "" },
        { "Sets T5", "" },
        { "Sets Zul'Gurub", "" },
    },
    {
        { "L'Aldor", "" },
        { "Aube d'argent", "" },
        { "La Voile sanglante", "Bloodsail1" },
        { "Prog\195\169niture de Nozdormu", "AQBroodRings" },
        { "Cercle c\195\169narien", "" },
        { "Exp\195\169dition c\195\169narienne", "" },
        { "Le Consortium", "" },
        { "Foire de Sombrelune", "Darkmoon" },
        { "Clan Loup-de-givre", "Frostwolf1" },
        { "Les Hydraxiens", "WaterLords1" },
        { "Bastion de l'honneur", "" },
        { "Gardiens du Temps", "KeepersofTime1" },
        { "Kurenai", "Kurenai1" },
        { "Ville basse", "" },
        { "Les Mag'har", "Maghar1" },
        { "La Balance des sables", "ScaleSands1" },
        { "Les Clairvoyants", "" },
        { "Les Sha'tar", "" },
        { "Sporeggar", "Sporeggar1" },
        { "Garde Foudrepique", "Stormpike1" },
        { "Confr\195\169rie du Thorium", "" },
        { "Thrallmar", "" },
        { "Repaire des Grumegueules", "Timbermaw" },
        { "Tranquillien", "Tranquillien1" },
        { "L'\197\146il pourpre", "VioletEye1" },
        { "Long-guet", "Wintersaber1" },
        { "Tribu Zandalar", "" },
    },
    {
		{ "R\195\169compenses Ar\195\168nes JcJ", "" },
        { "Vall\195\169e d\'Alterac", "" },
        { "Bassin d\'Arathi", "" },
        { "Les fortifications des flammes infernales (Alliance)", "HellAlliance" },
        { "Les fortifications des flammes infernales (Horde)", "HellHorde" },
        { "Nagrand: Halaa", "Nagrand" },
        { "Acc\195\169ssoires JcJ (Level 70)", "PvP70Accessories" },
        { "Epiques JcJ hors Sets", "" },
        { "R\195\169compenses JcJ (Niveau 60)", "" },
        { "R\195\169compenses JcJ (Niveau 70)", "" },
        { "For\195\170t de Terokkar: Tour des esprits", "Terokkar" },
        { "Goulet des Warsong", "" },
        { "Mar\195\169cage de Zangar: Ruines des fl\195\168ches jumelles", "Zangarmarsh" },
    },
};

AtlasLoot_Bosses = {
    ["Auch: Tombe-Mana"] = {
        { "Pandemonius", "AuchManaPandemonius" },
        { "Tavarok", "AuchManaTavarok" },
        { "Prince-nexus Shaffar", "AuchManaNexusPrince" },
    },
    ["Auch: Cryptes Auchenaï"] = {
        { "Shirrak le Veillemort", "AuchCryptsShirrak" },
        { "Exarque Maladaar", "AuchCryptsExarch" },        
    },
    ["Auch: Salles des Sethekk"] = {
        { "Tisseur d'ombre Syth", "AuchSethekkDarkweaver" },
        { "Roi-serre Ikiss", "AuchSethekkTalonKing" },
    },
    ["Auch: Le Labyrinthe des Ombres"] = {
        { "Ambassadeur Gueule-d'enfer", "AuchShadowHellmaw" },
        { "Coeur-noir le S\195\169ditieux", "AuchShadowBlackheart" },
        { "Grand Ma\195\174tre Vorpil", "AuchShadowGrandmaster" },
        { "Marmon", "AuchShadowMurmur" },
    },
    ["Profondeurs de Brassenoire"] = {
        { "Ghamoo-ra", "BFDGhamoora" },
        { "Dame Sarevess", "BFDLadySarevess" },
        { "Gelihast", "BFDGelihast" },
        { "Baron Aquanis", "BFDBaronAquanis" },
        { "Seigneur Kelris Cr\195\169pusculaire", "BFDTwilightLordKelris" },
        { "Vieux Serra'kis", "BFDOldSerrakis" },
        { "Aku'mai", "BFDAkumai" },
        { "Trash Mobs", "BFDTrash" },
    },
    ["Profondeurs de Rochenoire"] = {
        { "Seigneur Roccor", "BRDLordRoccor" },
        { "Grand Interrogateur Gerstahn", "BRDHighInterrogatorGerstahn" },
        { "L\'Ar\195\168ne, Theldren", "BRDArena" },
        { "Theldren", "BRDTheldren" },
        { "Houndmaster Grebmar", "BRDHoundmaster" },
        { "Pyromancier Loregrain (rare)", "BRDPyromantLoregrain" },
        { "La chambre forte", "BRDWarderStilgiss" },
        { "Fineous Darkvire", "BRDFineousDarkvire" },
        { "Seigneur Incendius", "BRDLordIncendius" },
        { "Bael'Gar", "BRDBaelGar" },
        { "G\195\169n\195\169ral Angerforge", "BRDGeneralAngerforge" },
        { "Seigneur Golem Argelmach", "BRDGolemLordArgelmach" },
        { "Grim Guzzler", "BRDGuzzler" },
        { "Ambassadeur Cingleflammes", "BRDFlamelash" },
        { "Panzor l\'Invincible (rare)", "BRDPanzor" },
        { "Le Tombeau des Sept", "BRDTomb" },
        { "Magmus", "BRDMagmus" },
        { "Empereur Dagran Thaurissan", "BRDImperatorDagranThaurissan" },
        { "Princesse Moira Bronzebeard", "BRDPrincess" },
        { "Trash Mobs", "BRDTrash" },
    },
    ["Pic de Rochenoire inf\195\169rieur"] = {
        { "G\195\169n\195\169ralissime Omokk", "LBRSOmokk" },
        { "Seigneur de guerre Spirestone (rare)", "LBRSSpirestoneLord" },
        { "Chasseur d\'ombres Vosh'gajin", "LBRSVosh" },
        { "Maitre de Guerre Voone", "LBRSVoone" },
        { "Mor Grayhoof", "LBRSGrayhoof" },
        { "Matriarche Couveuse", "LBRSSmolderweb" },
        { "Croc Cristalin (rare)", "LBRSCrystalFang" },
        { "Urok Hurleruine", "LBRSDoomhowl" },
        { "Intendant Zigris", "LBRSZigris" },
        { "Gizrul l'Esclavagiste", "LBRSSlavener" },
        { "Halycon", "LBRSHalycon" },
        { "Seigneur Wyrmthalak", "LBRSWyrmthalak" },
        { "Bannok Grimaxe", "LBRSGrimaxe" },
        { "Boucher Spirestone (rare)", "LBRSSpirestoneButcher" },
        { "Trash Mobs", "LBRSTrash" },
    },
    ["Pic de Rochenoire sup\195\169rieur"] = {
        { "Pyrogarde Proph\195\168te Ardent", "UBRSEmberseer" },
        { "Solakar Voluteflamme", "UBRSSolakar" },
        { "Flamme du p\195\168re", "UBRSFLAME" },
        { "Jed Runewatcher", "UBRSRunewatcher" },
        { "Goraluk Anvilcrack", "UBRSAnvilcrack" },
        { "Rend Blackhand", "UBRSRend" },
        { "Gyth", "UBRSGyth" },
        { "La B\195\170te", "UBRSBeast" },
        { "Seigneur Valthalak", "UBRSValthalak" },
        { "G\195\169n\195\169ral Drakkisath", "UBRSDrakkisath" },
        { "Trash Mobs", "UBRSTrash" },
    },
    ["Repaire de l\'Aile noire"] = {
        { "Tranchetripe l'Indompt\195\169", "BWLRazorgore" },
        { "Vaelastrasz le Corrompu", "BWLVaelastrasz" },
        { "Seigneur des couv\195\169es Lashlayer", "BWLLashlayer" },
        { "Gueule de Feu", "BWLFiremaw" },
        { "Roch\195\169b\195\168ne", "BWLEbonroc" },
        { "Flamegor", "BWLFlamegor" },
        { "Chromaggus", "BWLChromaggus" },
        { "Nefarian", "BWLNefarian" },
        { "Trash Mobs", "BWLTrashMobs" },
    },
    ["RdG: Les Enclos aux Esclaves"] = {
        { "Mennu le Tra\195\174tre", "CFRSlaveMennu" },
        { "Rokmar le Cr\195\169pitant", "CFRSlaveRokmar" },
        { "Bourbierreux", "CFRSlaveQuagmirran" },
    },
    ["RdG: La Basse Tourbi\195\168re"] = {
        { "Hungarfen", "CFRUnderHungarfen" },
        { "Ghaz'an", "CFRUnderGhazan" },
        { "Seigneur des marais Musel'ek", "CFRUnderSwamplord" },
        { "La Traqueuse noire", "CFRUnderStalker" },
    },
    ["RdG: Le Caveau de la Vapeur"] = {
        { "Hydromancienne Thespia", "CFRSteamThespia" },
        { "M\195\169kg\195\169nieur Montevapeur", "CFRSteamSteamrigger" },
        { "Seigneur de guerre Kalithresh", "CFRSteamWarlord" },
    },
	["RdG: Sanctuaire du Serpent"] = { -- à traduire
		{ "Hydross the Unstable", "CFRSerpentHydross" },
		{ "Fathom-Lord Karathress", "CFRSerpentKarathress" },
		{ "Morogrim Tidewalker", "CFRSerpentMorogrim" },
		{ "Leotheras the Blind", "CFRSerpentLeotheras" },
		{ "Lady Vashj", "CFRSerpentVashj" },
	},
    ["GdT: Les Contreforts d'Hautebrande d'antan"] = {
        { "Lieutenant Drake", "CoTHillsbradDrake" },
        { "Capitaine Skarloc", "CoTHillsbradSkarloc" },
        { "Chasseur d'\195\169poques", "CoTHillsbradHunter" },
    },
    ["GdT: Les Morasses Noires"] = {
        { "Chronoseigneur D\195\169j\195\160", "CoTMorassDeja" },
        { "Temporus", "CoTMorassTemporus" },
        { "Aeonus", "CoTMorassAeonus" },
    },
    ["Les Mortemines"] = {
        { "Rhahk'Zor", "VCRhahkZor" },
        { "Mineur Johnson (rare)", "VCMinerJohnson" },
        { "Sneed", "VCSneed" },
        { "Gilnid", "VCGilnid" },
        { "Capitaine Vertepeau", "VCCaptainGreenskin" },
        { "Edwin VanCleef", "VCVanCleef" },
        { "Mr. Smite", "VCMrSmite" },
        { "Macaron", "VCCookie" },
        { "Set: Cuir Defias", "VCDefiasSET" },
    },
    ["Hache-Tripes (Est)"] = {
        { "Pusillin", "DMEPusillin" },
        { "Zevrim Thornhoof", "DMEZevrimThornhoof" },
        { "Hydrog\195\169nos", "DMEHydro" },
        { "Lethtendris", "DMELethtendris" },
        { "Alzzin le modeleur", "DMEAlzzin" },
        { "Isalien", "DMEIsalien" },
        { "Trash Mobs", "DMETrash" },
        { "Livre de Hache-Tripes", "DMBooks" },
    },
    ["Hache-Tripes (Nord)"] = {
        { "Garde Mol'dar", "DMNGuardMoldar" },
        { "Kreeg le marteleur", "DMNStomperKreeg" },
        { "Garde Fengus", "DMNGuardFengus" },
        { "Knot Thimblejack", "DMNThimblejack" },
        { "Garde Slip'kik", "DMNGuardSlipkik" },
        { "Captaine Kromcrush", "DMNCaptainKromcrush" },
        { "Roi Gordok", "DMNKingGordok" },
        { "Tribute Run", "DMNTRIBUTERUN" },
        { "Livre de Hache-Tripes", "DMBooks" },
    },
    ["Hache-Tripes (Ouest)"] = {
        { "Tendris Crochebois", "DMWTendrisWarpwood" },
        { "Illyanna Ravenoak", "DMWIllyannaRavenoak" },
        { "Magistrat Kalendris", "DMWMagisterKalendris" },
        { "Tsu'Zee", "DMWTsuzee" },
        { "Immol'thar", "DMWImmolthar" },
        { "Seigneur Hel'nurath", "DMWHelnurath" },
        { "Prince Tortheldrin", "DMWPrinceTortheldrin" },
        { "Trash Mobs", "DMWTrash" },
        { "Livre de Hache-Tripes", "DMBooks" },
    },
    ["Gnomeregan"] = {
        { "Retomb\195\169es Visqueuses", "GnViscousFallout" },
        { "Grubbis", "GnGrubbis" },
        { "Electrocuteur 6000", "GnElectrocutioner6000" },
        { "Mekgineer Thermaplugg", "GnMekgineerThermaplugg" },
        { "Ambassadeur Dark Iron (rare)", "GnDIAmbassador" },
        { "Faucheur de foule 9-60", "GnCrowdPummeler960" },
        { "Trash Mobs", "GnTrash" },
    },
    ["Repaire de Gruul"] = {
        { "Haut Roi Maulgar", "GruulsLairHighKingMaulgar" },
		{ "Gruul le Tue-dragon", "GruulGruul" },
    },
    ["CFI: Remparts des Flammes infernales"] = {
        { "Gardien des guetteurs Gargolmar", "HCRampWatchkeeper" },
        { "Omor l'Intouch\195\169", "HCRampOmor" },
        { "Vazruden le Héraut", "HCRampVazruden" },
        { "Nazan", "HCRampNazan" },
        { "Reinforced Fel Iron Chest", "HCRampFelIronChest" },
    },
    ["CFI: La Fournaise du sang"] = {
        { "Le Faiseur", "HCFurnaceMaker" },
        { "Broggok", "HCFurnaceBroggok" },
        { "Keli'dan le Briseur", "HCFurnaceBreaker" },
    },
    ["CFI: Les Salles bris\195\169es"] = {
        { "Grand d\195\169moniste N\195\169anath\195\168me", "HCHallsNethekurse" },
        { "Porteguerre O'mrogg", "HCHallsOmrogg" },
        { "Chef de guerre Kargath Lamepoing", "HCHallsKargath" },
    },
    ["Karazhan"] = {
        { "Attumen le Veneur", "KaraAttumen" },
        { "Moroes", "KaraMoroes" },
        { "Damoiselle de vertu", "KaraMaiden" },
        { "Opera Event", "KaraOperaEvent" },
        { "Le conservateur", "KaraCurator" },
        { "Terestian Malsabot", "KaraIllhoof" },
        { "Ombre d'Aran", "KaraAran" },
        { "D\195\169dain-du-N\195\169ant", "KaraNetherspite" },
        { "Plaie-de-nuit", "KaraNightbane" },
        { "Prince Malchezaar", "KaraPrince" },
	{ "Trash Mobs", "KaraTrash" },
	{ "Chess Event", "KaraChess" },
	{ "Named Beasts", "KaraNamed" },
    },
    ["Maraudon"] = {
        { "Noxxion", "MaraNoxxion" },
        { "Tranchefouet", "MaraRazorlash" },
        { "Seigneur Vylelangue", "MaraLordVyletongue" },
        { "Meshlok le collecteur (rare)", "MaraMeshlok" },
        { "Celebras le maudit", "MaraCelebras" },
        { "Glissement de terrain", "MaraLandslide" },
        { "Artisan Gizlock", "MaraTinkererGizlock" },
        { "Rotgrip", "MaraRotgrip" },
        { "Princesse Theradras", "MaraPrincessTheradras" },
    },
    ["C\197\147ur du Magma"] = {
        { "Lucifron", "MCLucifron" },
        { "Magmadar", "MCMagmadar" },
        { "Gehennas", "MCGehennas" },
        { "Garr", "MCGarr" },
        { "Shazzrah", "MCShazzrah" },
        { "Baron Geddon", "MCGeddon" },
        { "Golemagg l\'Incin\195\169rateur", "MCGolemagg" },
        { "Messager de Sulfuron", "MCSulfuron" },
        { "Chambellan Executus", "MCMajordomo" },
        { "Ragnaros", "MCRagnaros" },
        { "Trash Mobs", "MCTrashMobs" },
        { "Drops al\195\169atoire des Boss", "MCRANDOMBOSSDROPPS" },
    },
    ["Naxxramas"] = {
        { "Le Recousu", "NAXPatchwerk" },
        { "Grobbulus", "NAXGrobbulus" },
        { "Gluth", "NAXGluth" },
        { "Thaddius", "NAXThaddius" },
        { "Anub'Rekhan", "NAXAnubRekhan" },
        { "Grande veuve Faerlina", "NAXGrandWidowFaerlina" },
        { "Maexxna", "NAXMaexxna" },
        { "Instructeur Razuvious", "NAXInstructorRazuvious" },
        { "Gothik le Moissonneur", "NAXGothikderHarvester" },
        { "Les quatre Cavaliers", "NAXTheFourHorsemen" },
        { "Noth le Porte-peste", "NAXNothderPlaguebringer" },
        { "Heigan l'Impur", "NAXHeiganderUnclean" },
        { "Loatheb", "NAXLoatheb" },
        { "Sapphiron", "NAXSapphiron" },
        { "Kel'Thuzad", "NAXKelThuzard" },
        { "Trash Mobs", "NAXTrash" },
    },
    ["Repaire d\'Onyxia"] = {
        { "Onyxia", "Onyxia" },
    },
    ["Gouffre de Ragefeu"] = {
        { "Taragaman l\'Affam\195\169", "RFCTaragaman" },
        { "Jergosh l\'Invocateur", "RFCJergosh" },
    },
    ["Souilles de Tranchebauge"] = {
        { "Tuten'kash", "RFDTutenkash" },
        { "Mordresh Oeil de Feu", "RFDMordreshFireEye" },
        { "Glutton", "RFDGlutton" },
        { "Ragglesnout (rare)", "RFDRagglesnout" },
        { "Amnennar le Porte-Froid", "RFDAmnennar" },
        { "Trash Mobs", "RFDTrash" },
    },
    ["Kraal de Tranchebauge"] = {
        { "M\195\169dium Jargba", "RFKDeathSpeakerJargba" },
        { "Seigneur Brusquebroche", "RFKOverlordRamtusk" },
        { "Agathelos l\'Enrag\195\169", "RFKAgathelos" },
        { "Chasseur Aveugle (rare)", "RFKBlindHunter" },
        { "Charlga Trancheflanc", "RFKCharlgaRazorflank" },
        { "Implorateur de la terre Halmgar (rare)", "RFKEarthcallerHalmgar" },
        { "Trash Mobs", "RFKTrash" },
    },
    ["Ruines d'Ahn'Qiraj"] = {
        { "Kurinnaxx", "AQ20Kurinnaxx" },
        { "G\195\169n\195\169ral de division Andorov", "AQ20Andorov" },
        { "Capitaines de Rajaxx", "AQ20CAPTIAN" },
        { "G\195\169n\195\169ral Rajaxx", "AQ20Rajaxx" },
        { "Moam", "AQ20Moam" },
        { "Buru Grandgosier", "AQ20Buru" },
        { "Ayamiss le chasseur", "AQ20Ayamiss" },
        { "Ossirian l'Intouch\195\169", "AQ20Ossirian" },
        { "Livres de classe", "AQ20ClassBooks" },
        { "Enchantements", "AQEnchants" },
    },
    ["Monast\195\168re \195\169carlate"] = {
        { "Maitre-Chien Loksey", "SMHoundmasterLoksey" },
        { "Arcaniste Doan", "SMDoan" },
        { "Herod", "SMHerod" },
        { "Grand Inquisiteur Fairbanks", "SMFairbanks" },
        { "Commandant Mograine", "SMMograine" },
        { "Grand Inquisiteur Whitemane", "SMWhitemane" },
        { "Ironspine (rare)", "SMIronspine" },
        { "Azshir le Sans-sommeil (rare)", "SMAzshir" },
        { "Champion Mort (rare)", "SMFallenChampion" },
        { "Mage de Sang Thalnos", "SMBloodmageThalnos" },
        { "Trash Mobs", "SMTrash" },
        { "Set: Cotte de mailles de la croisade \195\169carlate", "SMScarletSET" },
    },
    ["Scholomance"] = {
        { "R\195\169gisseur sanglant de Kirtonos",  "SCHOLOBloodSteward" },
        { "Kirtonos le H\195\169rault", "SCHOLOKirtonostheHerald" },
        { "Jandice Barov", "SCHOLOJandiceBarov" },
        { "Cliquetripes", "SCHOLORattlegore" },
        { "Chevalier de la mort Darkreaver", "SCHOLODeathKnight" },
        { "Marduk Noir\195\169tang", "SCHOLOMarduk" },
        { "Vectus", "SCHOLOVectus" },
        { "Ras Murmegivre", "SCHOLORasFrostwhisper" },
        { "Kormok", "SCHOLOKormok" },
        { "Instructeur Malicia", "SCHOLOInstructorMalicia" },
        { "Docteur Theolen Krastinov", "SCHOLODoctorTheolenKrastinov" },
        { "Gardien du Savoir Polkelt", "SCHOLOLorekeeperPolkelt" },
        { "Le Voracien", "SCHOLOTheRavenian" },
        { "Seigneur Alexei Barov", "SCHOLOLordAlexeiBarov" },
        { "Dame Illucia Barov", "SCHOLOLadyIlluciaBarov" },
        { "Sombre Maitre Gandling", "SCHOLODarkmasterGandling" },
        { "Trash Mobs", "SCHOLOTrash" },
    },
    ["Donjon d\'Ombrecroc"] = {
        { "Razorclaw le Boucher", "BSFRazorclawtheButcher" },
        { "Baron Silverlaine", "BSFSilverlaine" },
        { "Commandant Springvale", "BSFSpringvale" },
        { "Odo l'Aveugle", "BSFOdotheBlindwatcher" },
        { "Fenrus le D\195\169voreur", "BSFFenrustheDevourer" },
        { "Maître-loup Nandos", "BSFWolfMasterNandos" },
        { "Archimage Arugal", "BSFArchmageArugal" },
        { "Trash Mobs", "BSFTrash" },
    },
    ["La Prison"] = {
        { "Kam Deepfury", "SWStKamDeepfury" },
        { "Bruegal Ironknuckle", "SWStBruegalIronknuckle" },
    },
    ["Stratholme"] = {
        { "Skul", "STRATSkull" },
        { "Stratholme Courier", "STRATStratholmeCourier" },
        { "Fras Siabi", "STRATFrasSiabi" },
        { "Hearthsinger Forresten", "STRATHearthsingerForresten" },
        { "Le Condamn\195\169", "STRATTheUnforgiven" },
        { "Timmy le Cruel", "STRATTimmytheCruel" },
        { "Maitre Cannonier Willey", "STRATCannonMasterWilley" },
        { "Archiviste Galford", "STRATArchivistGalford" },
        { "Balnazzar", "STRATBalnazzar" },
        { "Sothos et Jarien", "STRATSothosJarien" },
        { "Stonespine", "STRATStonespine" },
        { "Barone Anastari", "STRATBaronessAnastari" },
        { "Nerub'enkan", "STRATNerubenkan" },
        { "Maleki le Blafard", "STRATMalekithePallid" },
        { "Magistrat Barthilas", "STRATMagistrateBarthilas" },
        { "Ramstein Grandgosier", "STRATRamsteintheGorger" },
        { "Baron Rivendare", "STRATBaronRivendare" },
        { "Trash Mobs", "STRATTrash" },
    },
    ["Le temple englouti"] = {
        { "Troll Miniboss", "STTrollMinibosses" },
        { "Atal'alarion", "STAtalalarion" },
        { "Fauche-r\195\170ve", "STDreamscythe" },
        { "Tisserand", "STWeaver"},
        { "Avatar d\'Hakkar", "STAvatarofHakkar" },
        { "Jammal'an le Proph\195\168te", "STJammalan" },
        { "Ogom le Corrompu", "STOgom" },
        { "Morphaz", "STMorphaz" },
        { "Hazzas", "STHazzas" },
        { "Ombre d\'Eranikus", "STEranikus" },
        { "Trash Mobs", "STTrash" },
    },
    ["Le temple d\'Ahn\'Qiraj"] = {
        { "Proph\195\168te Skeram", "AQ40Skeram" },
        { "La famille Insecte", "AQ40Vem" },
        { "Garde de guerre Sartura", "AQ40Sartura" },
        { "Fankriss l'Inflexible", "AQ40Fankriss" },
        { "Viscidus", "AQ40Viscidus" },
        { "Princesse Huhuran", "AQ40Huhuran" },
        { "Les Empereurs Jumeaux", "AQ40Emperors" },
        { "Ouro", "AQ40Ouro" },
        { "C'Thun", "AQ40CThun" },
        { "Trash Mobs", "AQ40Trash" },
        { "Enchantements", "AQEnchants" },
        { "Event de l'ouverture d\'AQ", "AQOpening" },
    },
    ["DT: L'Arcatraz"] = {
        { "Zereketh le D\195\169li\195\169", "TKArcUnbound" },
        { "Scrute-courroux Soccothrates", "TKArcScryer" },
        { "Dalliah l'Auspice-funeste", "TKArcDalliah" },
        { "Messager Cieuriss", "TKArcHarbinger" },
    },
    ["DT: La Botanica"] = {
        { "Commandant Sarannis", "TKBotSarannis" },
        { "Grand botaniste Freywinn", "TKBotFreywinn" },
        { "Rir\195\169pine le Tendre", "TKBotThorngrin" },
        { "Laj", "TKBotLaj" },
        { "Brise-dimension", "TKBotSplinter" },
    },
    ["DT: Le Mechanar"] = {
        { "Gardien de porte Gyro-Meurtre", "TKMechGyro" },
        { "Gardien de porte Main-en-fer", "TKMechIron" },
		{ "Cache of the Legion", "TKMechCacheoftheLegion" }, -- à traduire
        { "M\195\169cano-seigneur Capacitus", "TKMechCapacitus" },
        { "N\195\169antomancien Sepethrea", "TKMechSepethrea" },
        { "Pathaleon le Calculateur", "TKMechCalc" },
    },
    ["Uldaman"] = {
        { "Revelosh", "UldRevelosh" },
        { "Ironaya", "UldIronaya" },
        { "Garde en pierre Antique", "UldAncientStoneKeeper" },
        { "Galgann Firehammer", "UldGalgannFirehammer" },
        { "Grimlok", "UldGrimlok" },
        { "Archaedas", "UldArchaedas" },
        { "Trash Mobs", "UldTrash" },
    },
    ["Cavernes des lamentations"] = {
        { "Seigneur Cobrahn", "WCLordCobrahn" },
        { "Dame Anacondra", "WCLadyAnacondra" },
        { "Kresh", "WCKresh" },
        { "Seigneur Pythas", "WCLordPythas" },
        { "Skum", "WCSkum" },
        { "Seigneur Serpentis", "WCLordSerpentis" },
        { "Verdan l'Immortel", "WCVerdan" },
        { "Mutanus le D\195\169voreur", "WCMutanus" },
        { "Dragon f\195\169\195\169rique D\195\169vian", "WCDeviateFaerieDragon" },
        { "Set: Etreinte de la vip\195\168re", "WCViperSET" },
    },
    ["Zul'Farrak"] = {
        { "Antu'sul", "ZFAntusul" },
        { "Sorcier-docteur Zum'rah", "ZFWitchDoctorZumrah" },
        { "Pr\195\170tre des ombres Sezz'ziz", "ZFSezzziz" },
        { "Gahz'rilla", "ZFGahzrilla" },
        { "Dustwraith", "ZFDustwraith" },
        { "Ukorz Scalpessable", "ZFChiefUkorzSandscalp" },
        { "Zerillis", "ZFZerillis" },
        { "Trash Mobs", "ZFTrash" },
    },
    ["Zul'Gurub"] = {
        { "Grande Pr\195\170tresse Jeklik", "ZGJeklik" },
        { "Grand Pr\195\170tre Venoxis", "ZGVenoxis" },
        { "Grande Pr\195\170tresse Mar'li", "ZGMarli" },
        { "Seigneur sanglant Mandokir", "ZGMandokir" },
        { "Gri'lek du Sang de fer", "ZGGrilek" },
        { "Hazza'rah Tisser\195\170ve", "ZGHazzarah" },
        { "Renataki des Mille lames", "ZGRenataki" },
        { "Wushoolay la Sorci\195\168re des temp\195\170tes", "ZGWushoolay" },
        { "Gahz'ranka", "ZGGahzranka" },
        { "Grand Pr\195\170tre Thekal", "ZGThekal" },
        { "Grande Pr\195\170tresse Arlokk", "ZGArlokk" },
        { "Jin'do le mal\195\169ficieur", "ZGJindo" },
        { "Hakkar", "ZGHakkar" },
        { "Butin Al\195\169atoire des Boss", "ZGShared" },
        { "Trash Mobs", "ZGTrash" },
        { "Enchantements", "ZGEnchants" },
    },
    ["Set Ar\195\168nes JcJ"] = {
        { "Druide", "ArenaDruid" },
        { "Chasseur", "ArenaHunter" },
        { "Mage", "ArenaMage" },
        { "Paladin", "ArenaPaladin" },
        { "Pr\195\170tre", "ArenaPriest" },
        { "Voleur", "ArenaRogue" },
        { "Chaman", "ArenaShaman" },
        { "D\195\169moniste", "ArenaWarlock" },
        { "Guerrier", "ArenaWarrior" },
    },
    ["Sets JcJ (Niveau 60)"] = {
        { "Druide", "PVPDruid" },
        { "Chasseur", "PVPHunter" },
        { "Mage", "PVPMage" },
        { "Paladin", "PVPPaladin" },
        { "Pr\195\170tre", "PVPPriest" },
        { "Voleur", "PVPRogue" },
        { "Chaman", "PVPShaman" },
        { "D\195\169moniste", "PVPWarlock" },
        { "Guerrier", "PVPWarrior" },
    },
    ["Sets JCJ (Niveau 70)"] = {
        { "Druide", "PVP70Druid" },
        { "Chasseur", "PVP70Hunter" },
        { "Mage", "PVP70Mage" },
        { "Paladin", "PVP70Paladin" },
        { "Pr\195\170tre", "PVP70Priest" },
        { "Voleur", "PVP70Rogue" },
        { "Chaman", "PVP70Shaman" },
        { "D\195\169moniste", "PVP70Warlock" },
        { "Guerrier", "PVP70Warrior" },
    },
    ["Sets des Ruines d'Ahn'Qiraj"] = {
        { "Druide", "AQ20Druid" },
        { "Chasseur", "AQ20Hunter" },
        { "Mage", "AQ20Mage" },
        { "Paladin", "AQ20Paladin" },
        { "Pr\195\170tre", "AQ20Priest" },
        { "Voleur", "AQ20Rogue" },
        { "Chaman", "AQ20Shaman" },
        { "D\195\169moniste", "AQ20Warlock" },
        { "Guerrier", "AQ20Warrior" },
    },
    ["Sets du Temple d'Ahn'Qiraj"] = {
        { "Druide", "AQ40Druid" },
        { "Chasseur", "AQ40Hunter" },
        { "Mage", "AQ40Mage" },
        { "Paladin", "AQ40Paladin" },
        { "Pr\195\170tre", "AQ40Priest" },
        { "Voleur", "AQ40Rogue" },
        { "Chaman", "AQ40Shaman" },
        { "D\195\169moniste", "AQ40Warlock" },
        { "Guerrier", "AQ40Warrior" },
    },
    ["Sets Zul'Gurub"] = {
        { "Druide", "ZGDruid" },
        { "Chasseur", "ZGHunter" },
        { "Mage", "ZGMage" },
        { "Paladin", "ZGPaladin" },
        { "Pr\195\170tre", "ZGPriest" },
        { "Voleur", "ZGRogue" },
        { "Chaman", "ZGShaman" },
        { "D\195\169moniste", "ZGWarlock" },
        { "Guerrier", "ZGWarrior" },
    },
    ["Sets Donjon 1/2"] = {
        { "Druide", "T0Druid" },
        { "Chasseur", "T0Hunter" },
        { "Mage", "T0Mage" },
        { "Paladin", "T0Paladin" },
        { "Pr\195\170tre", "T0Priest" },
        { "Voleur", "T0Rogue" },
        { "Chaman", "T0Shaman" },
        { "D\195\169moniste", "T0Warlock" },
        { "Guerrier", "T0Warrior" },
    },
    ["Sets Donjon 3"] = {
        { "Grande tenue b\195\169nie (Tissu)", "DS3Hallowed" },
        { "Tenue de parade d'incantateur (Tissu)", "DS3Incanter" },
        { "Tenue de parade grav\195\169e au mana (Tissu)", "DS3Mana" },
        { "Grande tenue de l'oubli (Tissu)", "DS3Oblivion" },
        { "Armure d'assassinat (Cuir)", "DS3Assassin" },
        { "Grande tenue de Reflet-de-lune (Cuir)", "DS3Moonglade" },
        { "Wastewalker Armor (Cuir)", "DS3Wastewalker" },
        { "Beast Lord Armor (Mailles)", "DS3Beast" },
        { "Desolation Battlegear (Mailles)", "DS3Desolation" },
        { "Tidefury Raiment (Mailles)", "DS3Tidefury" },
        { "Bold Armor (Plaques)", "DS3Bold" },
        { "Doomplate Battlegear (Plaques)", "DS3Doom" },
        { "Righteous Armor (Plaques)", "DS3Right" },
    },
    ["Sets T1"] = {
        { "Druide", "T1Druid" },
        { "Chasseur", "T1Hunter" },
        { "Mage", "T1Mage" },
        { "Paladin", "T1Paladin" },
        { "Pr\195\170tre", "T1Priest" },
        { "Voleur", "T1Rogue" },
        { "Chaman", "T1Shaman" },
        { "D\195\169moniste", "T1Warlock" },
        { "Guerrier", "T1Warrior" },
    },
    ["Sets T2"] = {
        { "Druide", "T2Druid" },
        { "Chasseur", "T2Hunter" },
        { "Mage", "T2Mage" },
        { "Paladin", "T2Paladin" },
        { "Pr\195\170tre", "T2Priest" },
        { "Voleur", "T2Rogue" },
        { "Chaman", "T2Shaman" },
        { "D\195\169moniste", "T2Warlock" },
        { "Guerrier", "T2Warrior" },
    },
    ["Sets T3"] = {
        { "Druide", "T3Druid" },
        { "Chasseur", "T3Hunter" },
        { "Mage", "T3Mage" },
        { "Paladin", "T3Paladin" },
        { "Pr\195\170tre", "T3Priest" },
        { "Voleur", "T3Rogue" },
        { "Chaman", "T3Shaman" },
        { "D\195\169moniste", "T3Warlock" },
        { "Guerrier", "T3Warrior" },
    },
    ["Sets T4"] = {
        { "Druide", "T4Druid" },
        { "Chasseur", "T4Hunter" },
        { "Mage", "T4Mage" },
        { "Paladin", "T4Paladin" },
        { "Pr\195\170tre", "T4Priest" },
        { "Voleur", "T4Rogue" },
        { "Chaman", "T4Shaman" },
        { "D\195\169moniste", "T4Warlock" },
        { "Guerrier", "T4Warrior" },
    },
    ["Sets T5"] = {
        { "Druide", "T5Druid" },
        { "Chasseur", "T5Hunter" },
        { "Mage", "T5Mage" },
        { "Paladin", "T5Paladin" },
        { "Pr\195\170tre", "T5Priest" },
        { "Voleur", "T5Rogue" },
        { "Chaman", "T5Shaman" },
        { "D\195\169moniste", "T5Warlock" },
        { "Guerrier", "T5Warrior" },
    },
    ["L'Aldor"] = {
        { "Amical/Honor\195\169", "Aldor1" },
        { "R\195\169v\195\169r\195\169/Exalt\195\169", "Aldor2" },
    },
    ["Aube d'argent"] = {
        { "Token Hand-Ins", "Argent1" },
        { "Amical/Honor\195\169", "Argent2" },
        { "R\195\169v\195\169r\195\169/Exalt\195\169", "Argent3" },
    },
    ["Cercle c\195\169narien"] = {
        { "Amical", "Cenarion1" },
        { "Honor\195\169", "Cenarion2" },
        { "R\195\169v\195\169r\195\169", "Cenarion3" },
        { "Exalt\195\169", "Cenarion4" },
    },
    ["Exp\195\169dition c\195\169narienne"] = {
        { "Amical/Honor\195\169", "CExpedition1" },
        { "R\195\169v\195\169r\195\169/Exalt\195\169", "CExpedition2" },
    },
    ["Le Consortium"] = {
        { "Amical/Honor\195\169", "Consortium1" },
        { "R\195\169v\195\169r\195\169/Exalt\195\169", "Consortium2" },
    },
    ["Bastion de l'honneur"] = {
        { "Amical/Honor\195\169", "HonorHold1" },
        { "R\195\169v\195\169r\195\169/Exalt\195\169", "HonorHold2" },
    },
    ["Ville basse"] = {
        { "Amical - R\195\169v\195\169r\195\169", "LowerCity1" },
        { "Exalt\195\169", "LowerCity2" },
    },
    ["Les Clairvoyants"] = {
        { "Amical/Honor\195\169", "Scryer1" },
        { "R\195\169v\195\169r\195\169/Exalt\195\169", "Scryer2" },
    },
    ["Les Sha'tar"] = {
        { "Amical - R\195\169v\195\169r\195\169", "Shatar1" },
        { "Exalt\195\169", "Shatar2" },
    },
    ["Confr\195\169rie du Thorium"] = {
        { "Amical/Honor\195\169", "Thorium1" },
        { "R\195\169v\195\169r\195\169/Exalt\195\169", "Thorium2" },
    },
    ["Thrallmar"] = {
        { "Amical/Honor\195\169", "Thrallmar1" },
        { "R\195\169v\195\169r\195\169/Exalt\195\169", "Thrallmar2" },
    },
    ["Tribu Zandalar"] = {
        { "Amical/Honor\195\169", "Zandalar1" },
        { "R\195\169v\195\169r\195\169/Exalt\195\169", "Zandalar2" },
    },
    ["Vall\195\169e d\'Alterac"] = {
       { ATLASLOOT_BG_MISC, "AVMisc" },
        { ATLASLOOT_BG_BLUE, "AVBlue" },
        { ATLASLOOT_BG_PURPLE, "AVPurple" },
    },
    ["Bassin d\'Arathi"] = {
        { "R\195\169compenses Diverses (Lvl 60)", "ABMisc" },
        { "R\195\169compenses Sup\195\169rieurs (Lvl 60)", "ABBlue" },
        { "R\195\169compenses Epiques (Lvl 60)", "ABPurple" },
    },
    ["R\195\169compenses Ar\195\168nes JcJ"] = {
        { "Druide", "ArenaDruid" },
        { "Chasseur", "ArenaHunter" },
        { "Mage", "ArenaMage" },
        { "Paladin", "ArenaPaladin" },
        { "Pr\195\170tre", "ArenaPriest" },
        { "Voleur", "ArenaRogue" },
        { "Chaman", "ArenaShaman" },
        { "D\195\169moniste", "ArenaWarlock" },
        { "Guerrier", "ArenaWarrior" },
        { "Armes", "ArenaWeapons" },
    },
    ["Epiques JcJ hors Sets"] = {
        { "Dos/Bracelets", "PvP70NonSet1" },
        { "Ceintures", "PvP70NonSet2" },
        { "Pieds", "PvP70NonSet3" },
    },
    ["R\195\169compenses JcJ (Niveau 60)"] = {
        { "Druide", "PVPDruid" },
        { "Chasseur", "PVPHunter" },
        { "Mage", "PVPMage" },
        { "Paladin", "PVPPaladin" },
        { "Pr\195\170tre", "PVPPriest" },
        { "Voleur", "PVPRogue" },
        { "Chaman", "PVPShaman" },
        { "D\195\169moniste", "PVPWarlock" },
        { "Guerrier", "PVPWarrior" },
        { "Armes 1", "PVPWeapons1" },
        { "Armes 2", "PVPWeapons2" },
    },
    ["R\195\169compenses JcJ (Niveau 70)"] = {
        { "Druide", "PVP70Druid" },
        { "Chasseur", "PVP70Hunter" },
        { "Mage", "PVP70Mage" },
        { "Paladin", "PVP70Paladin" },
        { "Pr\195\170tre", "PVP70Priest" },
        { "Voleur", "PVP70Rogue" },
        { "Chaman", "PVP70Shaman" },
        { "D\195\169moniste", "PVP70Warlock" },
        { "Guerrier", "PVP70Warrior" },
        { "Armes 1", "PVP70Weapons1" },
        { "Armes 2", "PVP70Weapons2" },
    },
    ["Goulet des Warsong"] = {
        { "R\195\169compenses Diverses (Lvl 60)", "WSGMisc" },
        { "R\195\169compenses Sup\195\169rieurs (Lvl 60)", "WSGBlue" },
        { "R\195\169compenses Epiques (Lvl 60)", "WSGPurple" },
    },
};

end
--[[
 à: C3 A0 - \195\160
 â: C3 A2 - \195\162
 ç: C3 A7 - \185\167
 è: C3 A8 - \195\168
 é: C3 A9 - \195\169
 ê: C3 AA - \195\170
 ë: C3 AB - \195\171
 î: C3 AE - \195\174
 ô: C3 B4 - \195\180
 û: C3 BB - \195\187
 œ: C5 93 - \197\147
--]]
