-- [[
-- Version: 2.04.00
-- Last Updated: 2/23/2007
-- Initial translation by: 560889223
-- Maintained by: Diablohu
-- ]]

if (GetLocale() == "zhCN") then

-----------------------
-- 经本地化的全局常量
-----------------------
ATLASLOOT_TITLE = "AtlasLoot";
ATLASLOOT_NOMATCH = "未找到物品";

ATLASLOOT_SEARCH = "搜索";
ATLASLOOT_CLEAR = "重置";

ATLASLOOT_FIRST_TIME_TEXT = "欢迎使用 Atlasloot Enhanced。现在请花一些时间来设置提示与物品连接的方式。\n\n  今后可以输入“/atlasloot”再次显示该设置窗口。";
ATLASLOOT_FIRST_TIME_BUTTON = "设置";

ATLASLOOT_OLD_ATLAS_TEXT_PT1 = "AtlasLoot 检测到您正在使用的 Atlas 插件的版本与 AtlasLoot 需要的版本（";
ATLASLOOT_OLD_ATLAS_TEXT_PT2 = "）不符。该情况下可能会频繁出现插件错误信息。鉴于此，请您立刻访问 http://www.atlasmod.com 更新您的 Atlas 版本。";
ATLASLOOT_OLD_ATLAS_BUTTON = "确定";

ATLASLOOT_DROP_RATE = "掉落率: ";
ATLASLOOT_DKP = "DKP";
ATLASLOOT_PRIORITY = "优先:";

ATLASLOOT_BANNER_TEXT = "点击首领名以浏览掉落";

ATLASLOOT_DEFAULTFRAME_NOTICE = "该窗口只是一个掉落浏览器。若想同时查看地图，请安装 Atlas 或 Alphmap 插件。";

ATLASLOOT_ERRORTOOLTIP_L1 = "不安全的物品";
ATLASLOOT_ERRORTOOLTIP_L2 = "ItemID:";
ATLASLOOT_ERRORTOOLTIP_L3 = "该物品连接不安全。若想得知此物品的属性又想避免掉线问题，您需要在游戏内见过一次该物品。这是暴雪在1.10版本中做出的强制性改动。";
ATLASLOOT_ERRORTOOLTIP_L4 = "您可以右键点击该物品以向服务器查询，但这样做有可能会与服务器断开连接。";

ATLASLOOT_PANEL_TOGGLE = "AtlasLoot 面板";

ATLASLOOT_SAFE_MESSAGE = "的连接是安全的";
ATLASLOOT_QUERY_MESSAGE = "已向服务器申请查询";
ATLASLOOT_RECLICK_MESSAGE = "。右键点击其他物品可刷新物品列表";

ATLASLOOT_UIBACK = "返回";

ATLASLOOT_CLOTH = "布甲";
ATLASLOOT_LEATHER = "皮甲";
ATLASLOOT_MAIL = "锁甲";
ATLASLOOT_PLATE = "板甲";

ATLASLOOT_HEAD = "头部";
ATLASLOOT_NECK = "颈部";
ATLASLOOT_SHOULDER = "肩部";
ATLASLOOT_BACK = "背部";
ATLASLOOT_CHEST = "胸部";
ATLASLOOT_SHIRT = "衬衣";
ATLASLOOT_TABARD = "公会徽章";
ATLASLOOT_WRIST = "手腕";
ATLASLOOT_HANDS = "手";
ATLASLOOT_WAIST = "腰部";
ATLASLOOT_LEGS = "腿部";
ATLASLOOT_FEET = "脚";
ATLASLOOT_RING = "手指";
ATLASLOOT_TRINKET = "饰品";
ATLASLOOT_OFF_HAND = "副手物品";
ATLASLOOT_RELIC = "圣物";

ATLASLOOT_ONE_HAND = "单手";
ATLASLOOT_TWO_HAND = "双手";
ATLASLOOT_MAIN_HAND = "主手";
ATLASLOOT_OFFHAND = "副手";

ATLASLOOT_WEAPONS = "武器";
ATLASLOOT_AXE = "斧";
ATLASLOOT_BOW = "弓";
ATLASLOOT_CROSSBOW = "弩";
ATLASLOOT_DAGGER = "匕首";
ATLASLOOT_GUN = "枪械";
ATLASLOOT_MACE = "锤";
ATLASLOOT_POLEARM = "长柄武器";
ATLASLOOT_SHIELD = "盾牌";
ATLASLOOT_STAFF = "法杖";
ATLASLOOT_SWORD = "剑";
ATLASLOOT_THROWN = "投掷武器";
ATLASLOOT_WAND = "魔杖";
ATLASLOOT_FIST = "拳套";

ATLASLOOT_POTION = "药水";
ATLASLOOT_FOOD = "食物";
ATLASLOOT_DRINK = "饮品";
ATLASLOOT_BANDAGE = "绷带";
ATLASLOOT_ARROW = "弓箭";
ATLASLOOT_BULLET = "子弹"
ATLASLOOT_MOUNT = "坐骑";
ATLASLOOT_AMMO = "弹药袋";
ATLASLOOT_QUIVER = "箭袋";
ATLASLOOT_BAG = "背包";
ATLASLOOT_ENCHANT = "附魔";
ATLASLOOT_TRADE_GOODS = "杂货";
ATLASLOOT_SCOPE = "瞄准镜";
ATLASLOOT_KEY = "钥匙";
ATLASLOOT_PET = "宠物";
ATLASLOOT_IDOL = "神像";
ATLASLOOT_TOTEM = "图腾";
ATLASLOOT_LIBRAM = "圣契";
ATLASLOOT_DARKMOON = "暗月马戏团卡片";
ATLASLOOT_BOOK = "书籍";
ATLASLOOT_BANNER = "旗帜";

ATLASLOOT_DRUID = "德鲁伊";
ATLASLOOT_HUNTER = "猎人";
ATLASLOOT_MAGE = "法师";
ATLASLOOT_PALADIN = "圣骑士";
ATLASLOOT_PRIEST = "牧师";
ATLASLOOT_ROGUE = "盗贼";
ATLASLOOT_SHAMAN = "萨满祭司";
ATLASLOOT_WARLOCK = "术士";
ATLASLOOT_WARRIOR = "战士";

ATLASLOOT_ALCHEMY = "炼金术";
ATLASLOOT_BLACKSMITHING = "锻造";
ATLASLOOT_COOKING = "烹饪";
ATLASLOOT_ENCHANTING = "附魔";
ATLASLOOT_ENGINEERING = "工程学";
ATLASLOOT_FIRST_AID = "急救";
ATLASLOOT_LEATHERWORKING = "制皮";
ATLASLOOT_TAILORING = "裁缝";
ATLASLOOT_DRAGONSCALE = "龙鳞";
ATLASLOOT_TRIBAL = "部族";
ATLASLOOT_ELEMENTAL = "元素";
ATLASLOOT_JEWELCRAFTING = "珠宝加工";

ATLASLOOT_NEUTRAL = "中立";
ATLASLOOT_FRIENDLY = "友善";
ATLASLOOT_HONORED = "尊敬";
ATLASLOOT_REVERED = "崇敬";
ATLASLOOT_EXALTED = "崇拜";

ATLASLOOT_CLASSES = "职业:";
ATLASLOOT_ITEMBEGINSQUEST = "该物品将触发一个任务";
ATLASLOOT_QUESTITEM = "任务物品";
ATLASLOOT_QUESTREWARD = "任务奖励";
ATLASLOOT_SHARED = "共享";
ATLASLOOT_HORDE = "部落";
ATLASLOOT_ALLIANCE = "联盟";
ATLASLOOT_UNIQUE = "唯一";
ATLASLOOT_RIGHTSIDE = "右半部分";
ATLASLOOT_LEFTSIDE = "左半部分";
ATLASLOOT_FELCOREBAG = "28格 灵魂袋";
ATLASLOOT_ONYBAG = "18格";
ATLASLOOT_WCBAG = "10格";
ATLASLOOT_FULLSKILL = "(300)";
ATLASLOOT_295 = "(295)";
ATLASLOOT_275 = "(275)";
ATLASLOOT_265 = "(265)";
ATLASLOOT_290 = "(290)";
ATLASLOOT_SET = "套装";
ATLASLOOT_285 = "(285)";
ATLASLOOT_16SLOT = "16格";
ATLASLOOT_GEM = "宝石";
ATLASLOOT_RANDOM = "(随机附魔)";

ATLASLOOT_LEVEL_60 = "等级 60";
ATLASLOOT_LEVEL_70 = "等级 70";

ATLASLOOT_VIPERSET = "套装：毒蛇的拥抱 (5件套)";
ATLASLOOT_COBRAHN = "掉落: 考布莱恩";
ATLASLOOT_ANACONDRA = "掉落: 安娜科德拉";
ATLASLOOT_SERPENTIS = "掉落: 瑟芬迪斯";
ATLASLOOT_FANGDRUID = "掉落: 尖牙德鲁伊";
ATLASLOOT_PYTHAS = "掉落: 皮萨斯";

ATLASLOOT_DEFIASSET = "套装：迪菲亚皮甲 (5件套)";
ATLASLOOT_VANCLEEF = "掉落: 艾德温·范克利夫";
ATLASLOOT_GREENSKIN = "掉落: 绿皮队长";
ATLASLOOT_DEFIASMINER = "掉落: 迪菲亚赤膊矿工";
ATLASLOOT_DEFIASOVERSEER = "掉落: 迪菲亚监工/工头";

ATLASLOOT_GLADIATORSET = "套装：角斗士";

ATLASLOOT_Primal_Hakkari_Kossack = "Primal Hakkari Kossack";
ATLASLOOT_Primal_Hakkari_Shawl = "Primal Hakkari Shawl";
ATLASLOOT_Primal_Hakkari_Bindings = "Primal Hakkari Bindings";
ATLASLOOT_Primal_Hakkari_Sash = "Primal Hakkari Sash";
ATLASLOOT_Primal_Hakkari_Stanchion = "Primal Hakkari Stanchion";
ATLASLOOT_Primal_Hakkari_Aegis = "Primal Hakkari Aegis";
ATLASLOOT_Primal_Hakkari_Girdle = "Primal Hakkari Girdle";
ATLASLOOT_Primal_Hakkari_Armsplint = "Primal Hakkari Armsplint";
ATLASLOOT_Primal_Hakkari_Tabard = "原始哈卡莱徽章";

ATLASLOOT_Qiraji_Ornate_Hilt = "Qiraji Ornate Hilt";
ATLASLOOT_Qiraji_Martial_Drape = "Qiraji Martial Drape";
ATLASLOOT_Qiraji_Magisterial_Ring = "Qiraji Magisterial Ring";
ATLASLOOT_Qiraji_Ceremonial_Ring = "Qiraji Ceremonial Ring";
ATLASLOOT_Qiraji_Regal_Drape = "Qiraji Regal Drape";
ATLASLOOT_Qiraji_Spiked_Hilt = "Qiraji Spiked Hilt";

ATLASLOOT_Qiraji_Bindings_of_Dominance = "Qiraji Bindings of Dominance";
ATLASLOOT_Veknilashs_Circlet = "Vek'nilash's Circlet";
ATLASLOOT_Ouros_Intact_Hide = "Ouro's Intact Hide";
ATLASLOOT_Husk_of_the_Old_God = "Husk of the Old God";
ATLASLOOT_Qiraji_Bindings_of_Command = "Qiraji Bindings of Command";
ATLASLOOT_Veklors_Diadem = "Vek'lor's Diadem";
ATLASLOOT_Skin_of_the_Great_Sandworm = "Skin of the Great Sandworm";
ATLASLOOT_Carapace_of_the_Old_God = "Carapace of the Old God";

ATLASLOOT_SCARLETSET = "套装：血色十字军链甲 (6件套)";
ATLASLOOT_SCARLETDEFENDER = "掉落: 血色防御者/仆从";
ATLASLOOT_SCARLETTRASH = "掉落: 所有普通怪物";
ATLASLOOT_SCARLETCHAMPION = "掉落: 血色勇士";
ATLASLOOT_SCARLETCENTURION = "掉落: 血色百夫长";
ATLASLOOT_SCARLETHEROD = "掉落: 赫洛德/莫格莱尼";
ATLASLOOT_SCARLETPROTECTOR = "掉落: 血色保卫者/卫兵";
ATLASLOOT_SCARLETINTERROGATOR = "审讯员韦沙斯";

ATLASLOOT_AQ40_SETS="安其拉神殿职业套装";
ATLASLOOT_AQ20_SETS="安其拉废墟职业套装";
ATLASLOOT_ZG_SETS="祖尔格拉布职业套装";
ATLASLOOT_TIER0_SETS="地下城套装1/2";
ATLASLOOT_DS3_SETS="地下城套装3";
ATLASLOOT_TIER1_SETS="等级1套装";
ATLASLOOT_TIER2_SETS="等级2套装";
ATLASLOOT_TIER3_SETS="等级3套装";
ATLASLOOT_DUNGEON3_SETS="地下城套装3";
ATLASLOOT_TIER4_SETS="等级4套装";
ATLASLOOT_TIER5_SETS="等级5套装";
ATLASLOOT_PVP_SETS="PvP奖励职业套装";
ATLASLOOT_PVP_WEAPONS="PvP奖励武器";
ATLASLOOT_PVP_ACCESSORIES="PvP奖励非套装部位";
ATLASLOOT_PVP_NONSET="PvP奖励非套装史诗级部件";
ATLASLOOT_ARENA_SETS="竞技场奖励职业套装";
ATLASLOOT_ARENA_WEAPONS="竞技场奖励武器";
ATLASLOOT_TIER_4="等级4套装";

ATLASLOOT_ZG_DRUID="占卜师套装";
ATLASLOOT_ZG_HUNTER="捕猎者套装";
ATLASLOOT_ZG_MAGE="幻术师套装";
ATLASLOOT_ZG_PALADIN="思考者护甲";
ATLASLOOT_ZG_PRIEST="忏悔者衣饰";
ATLASLOOT_ZG_ROGUE="狂妄者套装";
ATLASLOOT_ZG_SHAMAN="预言者套装";
ATLASLOOT_ZG_WARLOCK="恶魔师护甲";
ATLASLOOT_ZG_WARRIOR="辩护者重甲";

ATLASLOOT_AQ20_DRUID="不灭的生命";
ATLASLOOT_AQ20_HUNTER="隐秘的通途";
ATLASLOOT_AQ20_MAGE="魔法的秘密";
ATLASLOOT_AQ20_PALADIN="永恒的公正";
ATLASLOOT_AQ20_PRIEST="无尽的智慧";
ATLASLOOT_AQ20_ROGUE="笼罩的阴影";
ATLASLOOT_AQ20_SHAMAN="聚集的风暴";
ATLASLOOT_AQ20_WARLOCK="禁断的邪语";
ATLASLOOT_AQ20_WARRIOR="坚定的力量";

ATLASLOOT_AQ40_DRUID="起源套装";
ATLASLOOT_AQ40_HUNTER="攻击者";
ATLASLOOT_AQ40_MAGE="神秘套装";
ATLASLOOT_AQ40_PALADIN="复仇者";
ATLASLOOT_AQ40_PRIEST="神谕者";
ATLASLOOT_AQ40_ROGUE="死亡执行者的拥抱";
ATLASLOOT_AQ40_SHAMAN="风暴召唤者";
ATLASLOOT_AQ40_WARLOCK="厄运召唤者";
ATLASLOOT_AQ40_WARRIOR="征服者";

ATLASLOOT_T0_DRUID="野性之心";
ATLASLOOT_T0_HUNTER="野兽追猎者";
ATLASLOOT_T0_MAGE="博学者的徽记";
ATLASLOOT_T0_PALADIN="光铸护甲";
ATLASLOOT_T0_PRIEST="虔诚";
ATLASLOOT_T0_ROGUE="迅影";
ATLASLOOT_T0_SHAMAN="元素";
ATLASLOOT_T0_WARLOCK="鬼雾";
ATLASLOOT_T0_WARRIOR="勇气";

ATLASLOOT_T05_DRUID="狂野之心";
ATLASLOOT_T05_HUNTER="兽王";
ATLASLOOT_T05_MAGE="巫师";
ATLASLOOT_T05_PALADIN="魂铸";
ATLASLOOT_T05_PRIEST="坚贞";
ATLASLOOT_T05_ROGUE="暗幕";
ATLASLOOT_T05_SHAMAN="五雷";
ATLASLOOT_T05_WARLOCK="死雾";
ATLASLOOT_T05_WARRIOR="英勇";

ATLASLOOT_T1_DRUID="塞纳里奥";
ATLASLOOT_T1_HUNTER="巨人追猎者";
ATLASLOOT_T1_MAGE="奥术师";
ATLASLOOT_T1_PALADIN="秩序之源";
ATLASLOOT_T1_PRIEST="预言";
ATLASLOOT_T1_ROGUE="夜幕杀手";
ATLASLOOT_T1_SHAMAN="大地之怒";
ATLASLOOT_T1_WARLOCK="恶魔之心";
ATLASLOOT_T1_WARRIOR="力量";

ATLASLOOT_T2_DRUID="怒风";
ATLASLOOT_T2_HUNTER="巨龙追猎者";
ATLASLOOT_T2_MAGE="灵风";
ATLASLOOT_T2_PALADIN="审判";
ATLASLOOT_T2_PRIEST="卓越";
ATLASLOOT_T2_ROGUE="血牙";
ATLASLOOT_T2_SHAMAN="无尽风暴";
ATLASLOOT_T2_WARLOCK="复仇";
ATLASLOOT_T2_WARRIOR="愤怒";

ATLASLOOT_T3_DRUID="梦游者";
ATLASLOOT_T3_HUNTER="地穴追猎者";
ATLASLOOT_T3_MAGE="霜火";
ATLASLOOT_T3_PALADIN="救赎";
ATLASLOOT_T3_PRIEST="信仰";
ATLASLOOT_T3_ROGUE="骨镰";
ATLASLOOT_T3_SHAMAN="碎地者";
ATLASLOOT_T3_WARLOCK="瘟疫之心";
ATLASLOOT_T3_WARRIOR="无畏";

ATLASLOOT_T4_DRUID_1="Malorne Harness";
ATLASLOOT_T4_DRUID_2="Malorne Raiment";
ATLASLOOT_T4_DRUID_3="Malorne Regalia";
ATLASLOOT_T4_HUNTER="Demon Stalker Armor";
ATLASLOOT_T4_MAGE="Aldor Regalia";
ATLASLOOT_T4_PALADIN_1="Justicar Armor";
ATLASLOOT_T4_PALADIN_2="Justicar Battlegear";
ATLASLOOT_T4_PALADIN_3="Justicar Raiment";
ATLASLOOT_T4_PRIEST_1="Incarnate Raiment";
ATLASLOOT_T4_PRIEST_2="Incarnate Regalia";
ATLASLOOT_T4_ROGUE="Netherblade Set";
ATLASLOOT_T4_SHAMAN_1="Cyclone Harness";
ATLASLOOT_T4_SHAMAN_2="Cyclone Raiment";
ATLASLOOT_T4_SHAMAN_3="Cyclone Regalia";
ATLASLOOT_T4_WARLOCK="Voidheart Raiment";
ATLASLOOT_T4_WARRIOR_1="Warbringer Armor";
ATLASLOOT_T4_WARRIOR_2="Warbringer Battlegear";

ATLASLOOT_T5_DRUID_1="Nordrassil Harness";
ATLASLOOT_T5_DRUID_2="Nordrassil Raiment";
ATLASLOOT_T5_DRUID_3="Nordrassil Regalia";
ATLASLOOT_T5_HUNTER="Rift Stalker Armor";
ATLASLOOT_T5_MAGE="Tirisfal Regalia";
ATLASLOOT_T5_PALADIN_1="Crystalforge Armor";
ATLASLOOT_T5_PALADIN_2="Crystalforge Battlegear";
ATLASLOOT_T5_PALADIN_3="Crystalforge Raiment";
ATLASLOOT_T5_PRIEST_1="Avatar Raiment";
ATLASLOOT_T5_PRIEST_2="Avatar Regalia";
ATLASLOOT_T5_ROGUE="Deathmantle Set";
ATLASLOOT_T5_SHAMAN_1="Cataclysm Harness";
ATLASLOOT_T5_SHAMAN_2="Cataclysm Raiment";
ATLASLOOT_T5_SHAMAN_3="Cataclysm Regalia";
ATLASLOOT_T5_WARLOCK="Corruptor Raiment";
ATLASLOOT_T5_WARRIOR_1="Destroyer Armor";
ATLASLOOT_T5_WARRIOR_2="Destroyer Battlegear";

ATLASLOOT_ARENA_DRUID_1="Gladiator's Sanctuary";
ATLASLOOT_ARENA_DRUID_2="Gladiator's Wildhide";
ATLASLOOT_ARENA_HUNTER="Gladiator's Pursuit";
ATLASLOOT_ARENA_MAGE="Gladiator's Regalia";
ATLASLOOT_ARENA_PALADIN_1="Gladiator's Aegis";
ATLASLOOT_ARENA_PALADIN_2="Gladiator's Vindication";
ATLASLOOT_ARENA_PRIEST="Gladiator's Raiment";
ATLASLOOT_ARENA_ROGUE="Gladiator's Vestments";
ATLASLOOT_ARENA_SHAMAN_1="Gladiator's Earthshaker";
ATLASLOOT_ARENA_SHAMAN_2="Gladiator's Thunderfist";
ATLASLOOT_ARENA_WARLOCK_1="Gladiator's Dreadgear";
ATLASLOOT_ARENA_WARLOCK_2="Gladiator's Felshroud";
ATLASLOOT_ARENA_WARRIOR="Gladiator's Battlegear";

ATLASLOOT_DS3_HALLOWED = "Hallowed Raiment";
ATLASLOOT_DS3_INCANTER = "Incanter's Regalia";
ATLASLOOT_DS3_MANA = "Mana-Etched Regalia";
ATLASLOOT_DS3_OBLIVION = "Oblivion Raiment";
ATLASLOOT_DS3_ASSASSIN = "Assassination Armor";
ATLASLOOT_DS3_MOONGLADE = "Moonglade Raiment";
ATLASLOOT_DS3_WASTEWALKER = "Wastewalker Armor";
ATLASLOOT_DS3_BEAST = "Beast Lord Armor";
ATLASLOOT_DS3_DESOLATION = "Desolation Battlegear";
ATLASLOOT_DS3_TIDEFURY = "Tidefury Raiment";
ATLASLOOT_DS3_BOLD = "Bold Armor";
ATLASLOOT_DS3_DOOM = "Doomplate Battlegear";
ATLASLOOT_DS3_RIGHT = "Righteous Armor";

ATLASLOOT_BROOD_CONQUEROR = "征服者之路";
ATLASLOOT_BROOD_INVOKER = "祈求者之路";
ATLASLOOT_BROOD_PROTECTOR = "保护者之路";

ATLASLOOT_AQ40_CLASS_SET_PIECES_1 = "X) 安其拉神殿职业套装";
ATLASLOOT_AQ40_BROOD_RINGS = "X) 诺兹多姆的子嗣奖励戒指";
ATLASLOOT_ZG_CLASS_SET_PIECES_1 = "X) 祖尔格拉布职业套装";
ATLASLOOT_AQ20_CLASS_SET_PIECES_1 = "X) 安其拉废墟职业套装";
ATLASLOOT_NAXX_SET_PIECES = "X) 等级3套装";
ATLASLOOT_BWL_SET_PIECES = "X) 等级2套装";
ATLASLOOT_MC_SET_PIECES = "X) 等级1套装";
ATLASLOOT_T0_SET_PIECES = "X) 地下城套装1/2";
ATLASLOOT_AQ_ENCHANTS = "X) 安其拉掉落的附魔公式";
ATLASLOOT_ZG_ENCHANTS = "X) 祖尔格拉布的附魔";
ATLASLOOT_CLASS_BOOKS = "X) 职业书籍";
ATLASLOOT_TRIBUTE_RUN = "X) 贡品";
ATLASLOOT_DM_BOOKS = "X) 厄运之槌书籍";
ATLASLOOT_TRASH_MOBS = "X) 普通怪物掉落物品";
ATLASLOOT_RANDOM_LOOT = "X) 首领随机掉落物品";
ATLASLOOT_CLASS_SET_PIECES = "X) 职业套装部件";
ATLASLOOT_NO_ITEMINFO = " |cffff0000(不安全)";

ATLASLOOT_BRDARENA1 = "阿努希尔";
ATLASLOOT_BRDARENA2 = "剜眼者";
ATLASLOOT_BRDARENA3 = "修行者高罗什";
ATLASLOOT_BRDARENA4 = "格里兹尔";
ATLASLOOT_BRDARENA5 = "爬行者赫杜姆";
ATLASLOOT_BRDARENA6 = "破坏者奥科索尔";

ATLASLOOT_ST1 = "Gasher";
ATLASLOOT_ST2 = "Hukku";
ATLASLOOT_ST3 = "Loro";
ATLASLOOT_ST4 = "Mijan";
ATLASLOOT_ST5 = "Zolo";
ATLASLOOT_ST6 = "Zul'Lor";

ATLASLOOT_OPTIONS_TITLE = "Atlasloot 设置";
ATLASLOOT_OPTIONS_SAFE_LINKS = "安全物品连接 |cff1eff00(推荐)|r";
ATLASLOOT_OPTIONS_ALL_LINKS = "使用所有连接 |cffff0000(后果自负)|r";
ATLASLOOT_OPTIONS_DEFAULT_TOOLTIPS = "默认提示样式";
ATLASLOOT_OPTIONS_LOOTLINK_TOOLTIPS = "Lootlink 提示样式 |cff1eff00(推荐)|r";
ATLASLOOT_OPTIONS_LOOTLINK_TOOLTIPS_DISABLED = "|cff9d9d9dLootlink 提示样式 (推荐)|r";
ATLASLOOT_OPTIONS_ITEMSYNC_TOOLTIPS = "ItemSync 提示样式";
ATLASLOOT_OPTIONS_ITEMSYNC_TOOLTIPS_DISABLED = "|cff9d9d9dItemSync 提示样式|r";
ATLASLOOT_OPTIONS_EQUIPCOMPARE = "使用装备比较";
ATLASLOOT_OPTIONS_EQUIPCOMPARE_DISABLED = "|cff9d9d9d使用装备比较|r";
ATLASLOOT_OPTIONS_OPAQUE = "禁用物品列表背景透明";
ATLASLOOT_OPTIONS_ITEMIDS = "永远显示物品ID";
ATLASLOOT_OPTIONS_HIDEPANEL = "隐藏 AtlasLoot 面板";
ATLASLOOT_OPTIONS_MINIMAP = "显示小地图图标";
ATLASLOOT_OPTIONS_MINIMAPPOS = "设置小地图图标位置";
ATLASLOOT_OPTIONS_DONE = "完成";

ATLASLOOT_BG_FRIENDLY = "友善声望奖励";
ATLASLOOT_BG_HONORED = "尊敬声望奖励";
ATLASLOOT_BG_REVERED = "崇敬声望奖励";
ATLASLOOT_BG_EXALTED = "崇拜声望奖励";
ATLASLOOT_BG_MISC = "其他奖励";
ATLASLOOT_BG_BLUE = "精良级别奖励";
ATLASLOOT_BG_PURPLE = "史诗级别奖励";

ATLASLOOT_BG_STORMPIKE = "雷矛卫队";
ATLASLOOT_BG_FROSTWOLF = "霜狼氏族";
ATLASLOOT_BG_SENTINELS = "银翼要塞";
ATLASLOOT_BG_OUTRIDERS = "战歌先锋";
ATLASLOOT_BG_ARATHOR = "阿拉索联军";
ATLASLOOT_BG_DEFILERS = "污染者";

ATLASLOOT_PVP_EPIC_H_DRUID = "督军的圣装";
ATLASLOOT_PVP_EPIC_H_HUNTER = "督军的猎装";
ATLASLOOT_PVP_EPIC_H_MAGE = "督军的法衣";
ATLASLOOT_PVP_EPIC_H_PRIEST = "督军的神服";
ATLASLOOT_PVP_EPIC_H_ROGUE = "督军的制服";
ATLASLOOT_PVP_EPIC_H_SHAMAN = "督军的震撼";
ATLASLOOT_PVP_EPIC_H_WARLOCK = "督军的魔装";
ATLASLOOT_PVP_EPIC_H_WARRIOR = "督军的战甲";
ATLASLOOT_PVP_EPIC_H_PALADIN = "督军的庇护";

ATLASLOOT_PVP_EPIC_A_DRUID = "元帅的圣装";
ATLASLOOT_PVP_EPIC_A_HUNTER = "元帅的猎装";
ATLASLOOT_PVP_EPIC_A_MAGE = "元帅的法衣";
ATLASLOOT_PVP_EPIC_A_PALADIN = "元帅的庇护";
ATLASLOOT_PVP_EPIC_A_PRIEST = "元帅的神服";
ATLASLOOT_PVP_EPIC_A_ROGUE = "元帅的制服";
ATLASLOOT_PVP_EPIC_A_WARLOCK = "元帅的魔装";
ATLASLOOT_PVP_EPIC_A_WARRIOR = "元帅的战甲";
ATLASLOOT_PVP_EPIC_A_SHAMAN = "元帅的震撼";

ATLASLOOT_PVP_RARE_H_DRUID = "勇士的庇护";
ATLASLOOT_PVP_RARE_H_HUNTER = "勇士的职责";
ATLASLOOT_PVP_RARE_H_MAGE = "勇士的秘密";
ATLASLOOT_PVP_RARE_H_PRIEST = "勇士的授权";
ATLASLOOT_PVP_RARE_H_ROGUE = "勇士的套装";
ATLASLOOT_PVP_RARE_H_SHAMAN = "勇士的风暴";
ATLASLOOT_PVP_RARE_H_WARLOCK = "勇士的鬼纹";
ATLASLOOT_PVP_RARE_H_WARRIOR = "勇士的战铠";
ATLASLOOT_PVP_RARE_H_PALADIN = "勇士的壁垒";

ATLASLOOT_PVP_RARE_A_DRUID = "少校的庇护";
ATLASLOOT_PVP_RARE_A_HUNTER = "少校的职责";
ATLASLOOT_PVP_RARE_A_MAGE = "少校的秘密";
ATLASLOOT_PVP_RARE_A_PALADIN = "少校的壁垒";
ATLASLOOT_PVP_RARE_A_PRIEST = "少校的授权";
ATLASLOOT_PVP_RARE_A_ROGUE = "少校的护卫";
ATLASLOOT_PVP_RARE_A_WARLOCK = "少校的鬼纹";
ATLASLOOT_PVP_RARE_A_WARRIOR = "少校的战铠";
ATLASLOOT_PVP_RARE_A_SHAMAN = "少校的风暴";

ATLASLOOT_PVP_70_A_DRUID_1 = "Grand Marshal's Sanctuary";
ATLASLOOT_PVP_70_H_DRUID_1 = "High Warlord's Sanctuary";
ATLASLOOT_PVP_70_A_DRUID_2 = "Grand Marshal's Wildhide";
ATLASLOOT_PVP_70_H_DRUID_2 = "High Warlord's Wildhide";
ATLASLOOT_PVP_70_A_HUNTER_1 = "Grand Marshal's Pursuit";
ATLASLOOT_PVP_70_H_HUNTER_1 = "High Warlord's Pursuit";
ATLASLOOT_PVP_70_A_MAGE_1 = "Grand Marshal's Regalia";
ATLASLOOT_PVP_70_H_MAGE_1 = "High Warlord's Regalia";
ATLASLOOT_PVP_70_A_PALADIN_1 = "Grand Marshal's Aegis";
ATLASLOOT_PVP_70_H_PALADIN_1 = "High Warlord's Aegis";
ATLASLOOT_PVP_70_A_PALADIN_2 = "Grand Marshal's Vindication";
ATLASLOOT_PVP_70_H_PALADIN_2 = "High Warlord's Vindication";
ATLASLOOT_PVP_70_A_PRIEST_1 = "Grand Marshal's Raiment";
ATLASLOOT_PVP_70_H_PRIEST_1 = "High Warlord's Raiment";
ATLASLOOT_PVP_70_A_ROGUE_1 = "Grand Marshal's Vestments";
ATLASLOOT_PVP_70_H_ROGUE_1 = "High Warlord's Vestments";
ATLASLOOT_PVP_70_A_SHAMAN_1 = "Grand Marshal's Earthshaker";
ATLASLOOT_PVP_70_H_SHAMAN_1 = "High Warlord's Earthshaker";
ATLASLOOT_PVP_70_A_SHAMAN_2 = "Grand Marshal's Thunderfist";
ATLASLOOT_PVP_70_H_SHAMAN_2 = "High Warlord's Thunderfist";
ATLASLOOT_PVP_70_A_WARLOCK_1 = "Grand Marshal's Dreadgear";
ATLASLOOT_PVP_70_H_WARLOCK_1 = "High Warlord's Dreadgear";
ATLASLOOT_PVP_70_A_WARRIOR_1 = "Grand Marshal's Battlegear";
ATLASLOOT_PVP_70_H_WARRIOR_1 = "High Warlord's Battlegear";

ATLASLOOT_PVP_SET_PIECES = "PvP奖励职业套装";
ATLASLOOT_PVP_SET_PIECES_HEADER = "PvP奖励";
ATLASLOOT_PVP_EPIC_SET = "史诗级套装";
ATLASLOOT_PVP_RARE_SET = "精良级套装";
ATLASLOOT_LEGENDARIES = "传奇物品";
ATLASLOOT_HARDMODE = "70级副本交换奖励";
ATLASLOOT_HARDMODE_SUB1 = "非套装与武器";
ATLASLOOT_HARDMODE_SUB2 = "火焰抗性装备";
ATLASLOOT_HEROIC = "英雄模式";
ATLASLOOT_RAREMOUNTS = "稀有坐骑";
ATLASLOOT_TABARDS = "公会徽章";

ATLASLOOT_PANEL_BUTTON_OPTIONS = "设置";
ATLASLOOT_PANEL_BUTTON_SETS = "套装";
ATLASLOOT_PANEL_BUTTON_REPUTATION = "阵营";
ATLASLOOT_PANEL_BUTTON_PVP = "PvP奖励";

ATLASLOOT_FACTION_DARKMOON = "暗月马戏团";
ATLASLOOT_FACTION_THORIUM = "瑟银兄弟会";
ATLASLOOT_FACTION_TIMBERMAW = "木喉要塞";
ATLASLOOT_FACTION_ARGENT = "银色黎明";
ATLASLOOT_FACTION_CENARION = "塞纳里奥议会";
ATLASLOOT_FACTION_BROOD = "诺兹多姆的子嗣";
ATLASLOOT_FACTION_ZANDALAR = "赞达拉部族";
ATLASLOOT_FACTION_CENARION_EXPEDITION = "The Cenarion Expedition";
ATLASLOOT_FACTION_SPOREGGAR = "The Sporeggar";
ATLASLOOT_FACTION_KURENAI = "The Kurenai";
ATLASLOOT_FACTION_MAGHAR = "The Mag'har";
ATLASLOOT_FACTION_TRANQ = "The Tranquillien";
ATLASLOOT_FACTION_HONOR_HOLD = "Honor Hold";
ATLASLOOT_FACTION_THRALLMAR = "Thrallmar";
ATLASLOOT_FACTION_SCRYER = "The Scryers";
ATLASLOOT_FACTION_ALDOR = "The Aldor";
ATLASLOOT_FACTION_CONSORTIUM = "The Consortium";
ATLASLOOT_FACTION_SHATAR = "The Sha'tar";
ATLASLOOT_FACTION_LOWERCITY = "The Lower City";
ATLASLOOT_FACTION_ALTERAC = "奥特兰克山谷";
ATLASLOOT_FACTION_ARATHI = "阿拉希盆地";
ATLASLOOT_FACTION_WARSONG = "战歌峡谷";
ATLASLOOT_FACTION_KEEPERS = "The Keepers of Time";
ATLASLOOT_FACTION_ARGENT_INSIGNIAS = "需要购买的奖励";
ATLASLOOT_FACTION_ARGENT_TOKEN = "Token Hand-Ins";
ATLASLOOT_FACTION_STORMPIKE = "雷矛卫队";
ATLASLOOT_FACTION_FROSTWOLF = "霜狼氏族";
ATLASLOOT_FACTION_WINTERSABER = "冬刃豹训练师";
ATLASLOOT_FACTION_VIOLETEYE = "The Violet Eye";
ATLASLOOT_FACTION_WATERLORDS = "海达希亚水元素";
ATLASLOOT_FACTION_PIRATES = "血帆海岛";
ATLASLOOT_FACTION_SCALE = "The Scale of the Sands";

ATLASLOOT_FACTION_VIOLETEYE_PROTECTOR = "Path of the Violet Protector";
ATLASLOOT_FACTION_VIOLETEYE_MAGE = "Path of the Violet Mage";
ATLASLOOT_FACTION_VIOLETEYE_ASSASSIN = "Path of the Violet Assassin";
ATLASLOOT_FACTION_VIOLETEYE_RESTORER = "Path of the Violet Restorer";

ATLASLOOT_RED_SCEPTER = "红色节杖碎片";
ATLASLOOT_BLUE_SCEPTER = "蓝色节杖碎片";
ATLASLOOT_GREEN_SCEPTER = "绿色节杖碎片";
ATLASLOOT_SCEPTER = "流沙节杖";
ATLASLOOT_AQ_OPENING = "X) 安其拉之门任务奖励";

ATLASLOOT_ZONE_HELLFIRE = "Hellfire Peninsula";
ATLASLOOT_ZONE_HELLFIRE_W_PVP_AL = "Hellfire Fortifications (Alliance)";
ATLASLOOT_ZONE_HELLFIRE_W_PVP_HO = "Hellfire Fortifications (Horde)";
ATLASLOOT_ZONE_ZANGAR = "Zangarmarsh";
ATLASLOOT_ZONE_ZANGAR_W_PVP = "Twin Spire Ruins";
ATLASLOOT_ZONE_TEROKKAR = "Terokkar Forest";
ATLASLOOT_ZONE_TEROKKAR_W_PVP = "Spirit Towers";
ATLASLOOT_ZONE_NAGRAND = "Nagrand";
ATLASLOOT_ZONE_NAGRAND_W_PVP = "Halaa";

ATLASLOOT_TOKENS = "Use to purchase rewards";
ATLASLOOT_TOKENS_HORDE = "Use to purchase rewards (Horde)";
ATLASLOOT_TOKENS_ALLIANCE = "Use to purchase rewards (Alliance)";
ATLASLOOT_TOKEN = "Token";
ATLASLOOT_CRAFTING = "原料";

ATLASLOOT_MINIMAPBUTTON_LINE1 = "|cff1eff00单击|r 浏览掉落表";
ATLASLOOT_MINIMAPBUTTON_LINE2 = "|cffff0000右键点击|r 进行设置";
ATLASLOOT_MINIMAPBUTTON_LINE2_ALT = "|cffff0000Shift-单击|r 进行设置";

ATLASLOOT_DUNGEONSET2BOSS = "地下城套装2任务首领";
ATLASLOOT_BRDCHEST = "七贤之箱";
ATLASLOOT_GUZZLER_BLACKBREATH = "霍尔雷·黑须";
ATLASLOOT_GUZZLER_PHALANX = "法拉克斯";
ATLASLOOT_GUZZLER_RIBBLY = "雷布里·斯库比格特";
ATLASLOOT_BRD_WARDER = "Warder Stilgiss";
ATLASLOOT_BRD_COFFER = "Dark Coffer";
ATLASLOOT_BRD_SAFE = "The Secret Safe";
ATLASLOOT_BRD_VAULT = "黑色宝库";
ATLASLOOT_BRD_VEREK = "Verek";
ATLASLOOT_DM_CHORUSH = "观察者克鲁什";
ATLASLOOT_DM_TANNIN = "Ogre Tannin Basket";
ATLASLOOT_DM_FENGUS = "Fengus's Chest";
ATLASLOOT_DM_PRINCE = "The Prince's Chest";
ATLASLOOT_GUZZLER_SPAZZRING = "Plugger Spazzring";
ATLASLOOT_SCARLET_DOAN = "Doan's Strongbox";
ATLASLOOT_SCARLET_TRAINEE = "Scarlet Trainee";
ATLASLOOT_SCHOLO_FROSTWHISPER = "Frostwhisper's Embalming Fluid";
ATLASLOOT_UBRS_BREASTPLATE = "Unforged Rune Covered Breastplate";
ATLASLOOT_STRAT_STRONGBOX = "Malor's Strongbox";
ATLASLOOT_STRAT_PAINTING = "Unfinished Painting";
ATLASLOOT_DM_FELVINE = "Felvine Shard";
ATLASLOOT_BRD_FLAMEKEEPER = "Shadowforge Flame Keeper";
ATLASLOOT_ULD_BAELOG = "巴尔洛戈";
ATLASLOOT_ULD_BAELOG_CHEST = "巴尔洛戈的箱子";
ATLASLOOT_ULD_OLAF = "奥拉夫";
ATLASLOOT_ULD_ERIK = "艾瑞克";
ATLASLOOT_BSF_FELSTEED = "Fel Steed";
ATLASLOOT_BSF_Deathsworn = "Deathsworn Captain";

ATLASLOOT_NAXX_DAMAGESCHOOL = "|cffcc9933伤害类型：冰霜";

ATLASLOOT_KARAOPERA_CRONE = "The Crone";
ATLASLOOT_KARAOPERA_WOLF = "The Big Bad Wolf";
ATLASLOOT_KARAOPERA_ROMULO = "Romulo";
ATLASLOOT_KARAOPERA_JULIANNE = "Julianne";
ATLASLOOT_KARAOPERA_SHARED = "Shared Drops";
ATLASLOOT_KARAOPERA_ROMEOANDJULIET = "Romeo & Juliet";
ATLASLOOT_KARAOPERA_WIZARDOFOZ = "Wizard of Oz";
ATLASLOOT_KARAOPERA_REDRIDINGHOOD = "Red Riding Hood";

ATLASLOOT_KARA_ANIMAL_1 = "Hyakiss the Lurker";
ATLASLOOT_KARA_ANIMAL_2 = "Rokad the Ravager";
ATLASLOOT_KARA_ANIMAL_3 = "Shadikith the Glider";

ATLASLOOT_KARA_ANIMAL_1_TYPE = "Spider";
ATLASLOOT_KARA_ANIMAL_2_TYPE = "Darkhound";
ATLASLOOT_KARA_ANIMAL_3_TYPE = "Bat";

end