
local AL = AceLibrary("AceLocale-2.2"):new("AtlasLoot");

GetSpellInfoVanillaDB = {
	["enchants"] = {
		[7421] = {
			["name"] = "Runed Copper Rod",
			["icon"] = "Interface\\Icons\\INV_Staff_Goldfeathered_01",
			["item"] = 6218,
		},
		[7418] = {
			["name"] = "Enchant Bracer - Minor Health",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[7428] = {
			["name"] = "Enchant Bracer - Minor Deflection",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[14293] = {
			["name"] = "Lesser Magic Wand",
			["icon"] = "Interface\\Icons\\INV_Staff_02",
			["item"] = 11287,
		},
		[7420] = {
			["name"] = "Enchant Chest - Minor Health",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[7443] = {
			["name"] = "Enchant Chest - Minor Mana",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[7426] = {
			["name"] = "Enchant Chest - Minor Absorption",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[25124] = {
			["name"] = "Minor Wizard Oil",
			["icon"] = "Interface\\Icons\\INV_Poison_MindNumbing",
			["item"] = 20744,
		},
		[7454] = {
			["name"] = "Enchant Cloak - Minor Resistance",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[7457] = {
			["name"] = "Enchant Bracer - Minor Stamina",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[7766] = {
			["name"] = "Enchant Bracer - Minor Spirit",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[7748] = {
			["name"] = "Enchant Chest - Lesser Health",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[14807] = {
			["name"] = "Greater Magic Wand",
			["icon"] = "Interface\\Icons\\INV_Staff_07",
			["item"] = 11288,
		},
		[7771] = {
			["name"] = "Enchant Cloak - Minor Protection",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[7779] = {
			["name"] = "Enchant Bracer - Minor Agility",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[7782] = {
			["name"] = "Enchant Bracer - Minor Strength",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[7776] = {
			["name"] = "Enchant Chest - Lesser Mana",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[7786] = {
			["name"] = "Enchant Weapon - Minor Beastslayer",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[7788] = {
			["name"] = "Enchant Weapon - Minor Striking",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[7795] = {
			["name"] = "Runed Silver Rod",
			["icon"] = "Interface\\Icons\\INV_Staff_01",
			["item"] = 6339,
		},
		[7793] = {
			["name"] = "Enchant 2H Weapon - Lesser Intellect",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[7745] = {
			["name"] = "Enchant 2H Weapon - Minor Impact",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13378] = {
			["name"] = "Enchant Shield - Minor Stamina",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13380] = {
			["name"] = "Enchant 2H Weapon - Lesser Spirit",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13419] = {
			["name"] = "Enchant Cloak - Minor Agility",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13421] = {
			["name"] = "Enchant Cloak - Lesser Protection",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13464] = {
			["name"] = "Enchant Shield - Lesser Protection",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[7859] = {
			["name"] = "Enchant Bracer - Lesser Spirit",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[7857] = {
			["name"] = "Enchant Chest - Health",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[7867] = {
			["name"] = "Enchant Boots - Minor Agility",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[7861] = {
			["name"] = "Enchant Cloak - Lesser Fire Resistance",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[7863] = {
			["name"] = "Enchant Boots - Minor Stamina",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13501] = {
			["name"] = "Enchant Bracer - Lesser Stamina",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13485] = {
			["name"] = "Enchant Shield - Lesser Spirit",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13522] = {
			["name"] = "Enchant Cloak - Lesser Shadow Resistance",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13536] = {
			["name"] = "Enchant Bracer - Lesser Strength",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13538] = {
			["name"] = "Enchant Chest - Lesser Absorption",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13503] = {
			["name"] = "Enchant Weapon - Lesser Striking",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13529] = {
			["name"] = "Enchant 2H Weapon - Lesser Impact",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13607] = {
			["name"] = "Enchant Chest - Mana",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13620] = {
			["name"] = "Enchant Gloves - Fishing",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13612] = {
			["name"] = "Enchant Gloves - Mining",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13617] = {
			["name"] = "Enchant Gloves - Herbalism",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[25125] = {
			["name"] = "Minor Mana Oil",
			["icon"] = "Interface\\Icons\\INV_Potion_98",
			["item"] = 20745,
		},
		[13628] = {
			["name"] = "Runed Golden Rod",
			["icon"] = "Interface\\Icons\\INV_Staff_10",
			["item"] = 11130,
		},
		[13626] = {
			["name"] = "Enchant Chest - Minor Stats",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13622] = {
			["name"] = "Enchant Bracer - Lesser Intellect",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[14809] = {
			["name"] = "Lesser Mystic Wand",
			["icon"] = "Interface\\Icons\\INV_Staff_02",
			["item"] = 11289,
		},
		[13635] = {
			["name"] = "Enchant Cloak - Defense",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13637] = {
			["name"] = "Enchant Boots - Lesser Agility",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13631] = {
			["name"] = "Enchant Shield - Lesser Stamina",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13640] = {
			["name"] = "Enchant Chest - Greater Health",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13642] = {
			["name"] = "Enchant Bracer - Spirit",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13644] = {
			["name"] = "Enchant Boots - Lesser Stamina",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13646] = {
			["name"] = "Enchant Bracer - Lesser Deflection",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13648] = {
			["name"] = "Enchant Bracer - Stamina",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[14810] = {
			["name"] = "Greater Mystic Wand",
			["icon"] = "Interface\\Icons\\INV_Wand_07",
			["item"] = 11290,
		},
		[13653] = {
			["name"] = "Enchant Weapon - Lesser Beastslayer",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13657] = {
			["name"] = "Enchant Cloak - Fire Resistance",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13655] = {
			["name"] = "Enchant Weapon - Lesser Elemental Slayer",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13659] = {
			["name"] = "Enchant Shield - Spirit",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13661] = {
			["name"] = "Enchant Bracer - Strength",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13663] = {
			["name"] = "Enchant Chest - Greater Mana",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13687] = {
			["name"] = "Enchant Boots - Lesser Spirit",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13689] = {
			["name"] = "Enchant Shield - Lesser Block",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13693] = {
			["name"] = "Enchant Weapon - Striking",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[21931] = {
			["name"] = "Enchant Weapon - Winter's Might",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[25126] = {
			["name"] = "Lesser Wizard Oil",
			["icon"] = "Interface\\Icons\\INV_Potion_103",
			["item"] = 20746,
		},
		[13698] = {
			["name"] = "Enchant Gloves - Skinning",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13700] = {
			["name"] = "Enchant Chest - Lesser Stats",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13702] = {
			["name"] = "Runed Truesilver Rod",
			["icon"] = "Interface\\Icons\\INV_Staff_11",
			["item"] = 11145,
		},
		[13695] = {
			["name"] = "Enchant 2H Weapon - Impact",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13746] = {
			["name"] = "Enchant Cloak - Greater Defense",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13794] = {
			["name"] = "Enchant Cloak - Resistance",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13822] = {
			["name"] = "Enchant Bracer - Intellect",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13815] = {
			["name"] = "Enchant Gloves - Agility",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13817] = {
			["name"] = "Enchant Shield - Stamina",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13836] = {
			["name"] = "Enchant Boots - Stamina",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13841] = {
			["name"] = "Enchant Gloves - Advanced Mining",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13846] = {
			["name"] = "Enchant Bracer - Greater Spirit",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13858] = {
			["name"] = "Enchant Chest - Superior Health",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13890] = {
			["name"] = "Enchant Boots - Minor Speed",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13868] = {
			["name"] = "Enchant Gloves - Advanced Herbalism",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13882] = {
			["name"] = "Enchant Cloak - Lesser Agility",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13887] = {
			["name"] = "Enchant Gloves - Strength",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13917] = {
			["name"] = "Enchant Chest - Superior Mana",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13915] = {
			["name"] = "Enchant Weapon - Demonslaying",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13931] = {
			["name"] = "Enchant Bracer - Deflection",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13905] = {
			["name"] = "Enchant Shield - Greater Spirit",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13933] = {
			["name"] = "Enchant Shield - Frost Resistance",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13935] = {
			["name"] = "Enchant Boots - Agility",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13937] = {
			["name"] = "Enchant 2H Weapon - Greater Impact",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13939] = {
			["name"] = "Enchant Bracer - Greater Strength",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13941] = {
			["name"] = "Enchant Chest - Stats",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13943] = {
			["name"] = "Enchant Weapon - Greater Striking",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13945] = {
			["name"] = "Enchant Bracer - Greater Stamina",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13947] = {
			["name"] = "Enchant Gloves - Riding Skill",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[13948] = {
			["name"] = "Enchant Gloves - Minor Haste",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[17181] = {
			["name"] = "Enchanted Leather",
			["icon"] = "Interface\\Icons\\INV_Misc_Rune_05",
			["item"] = 12810,
		},
		[17180] = {
			["name"] = "Enchanted Thorium",
			["icon"] = "Interface\\Icons\\INV_Ingot_Eternium",
			["item"] = 12655,
		},
		[25127] = {
			["name"] = "Lesser Mana Oil",
			["icon"] = "Interface\\Icons\\INV_Potion_99",
			["item"] = 20747,
		},
		[20008] = {
			["name"] = "Enchant Bracer - Greater Intellect",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20009] = {
			["name"] = "Enchant Bracer - Superior Spirit",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20010] = {
			["name"] = "Enchant Bracer - Superior Strength",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20011] = {
			["name"] = "Enchant Bracer - Superior Stamina",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20012] = {
			["name"] = "Enchant Gloves - Greater Agility",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20013] = {
			["name"] = "Enchant Gloves - Greater Strength",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20014] = {
			["name"] = "Enchant Cloak - Greater Resistance",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20015] = {
			["name"] = "Enchant Cloak - Superior Defense",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20016] = {
			["name"] = "Enchant Shield - Superior Spirit",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20017] = {
			["name"] = "Enchant Shield - Greater Stamina",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20020] = {
			["name"] = "Enchant Boots - Greater Stamina",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[15596] = {
			["name"] = "Smoking Heart of the Mountain",
			["icon"] = "Interface\\Icons\\INV_Misc_Gem_Bloodstone_01",
			["item"] = 11811,
		},
		[13898] = {
			["name"] = "Enchant Weapon - Fiery Weapon",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[25128] = {
			["name"] = "Wizard Oil",
			["icon"] = "Interface\\Icons\\INV_Potion_104",
			["item"] = 20750,
		},
		[20023] = {
			["name"] = "Enchant Boots - Greater Agility",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20024] = {
			["name"] = "Enchant Boots - Spirit",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20025] = {
			["name"] = "Enchant Chest - Greater Stats",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20026] = {
			["name"] = "Enchant Chest - Major Health",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20028] = {
			["name"] = "Enchant Chest - Major Mana",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20029] = {
			["name"] = "Enchant Weapon - Icy Chill",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20030] = {
			["name"] = "Enchant 2H Weapon - Superior Impact",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20031] = {
			["name"] = "Enchant Weapon - Superior Striking",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20032] = {
			["name"] = "Enchant Weapon - Lifestealing",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20033] = {
			["name"] = "Enchant Weapon - Unholy Weapon",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20034] = {
			["name"] = "Enchant Weapon - Crusader",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20035] = {
			["name"] = "Enchant 2H Weapon - Major Spirit",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20036] = {
			["name"] = "Enchant 2H Weapon - Major Intellect",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[20051] = {
			["name"] = "Runed Arcanite Rod",
			["icon"] = "Interface\\Icons\\INV_Wand_09",
			["item"] = 16207,
		},
		[27837] = {
			["name"] = "Enchant 2H Weapon - Agility",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[23799] = {
			["name"] = "Enchant Weapon - Strength",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[23800] = {
			["name"] = "Enchant Weapon - Agility",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[23801] = {
			["name"] = "Enchant Bracer - Mana Regeneration",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[23802] = {
			["name"] = "Enchant Bracer - Healing Power",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[23803] = {
			["name"] = "Enchant Weapon - Mighty Spirit",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[23804] = {
			["name"] = "Enchant Weapon - Mighty Intellect",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[25130] = {
			["name"] = "Brilliant Mana Oil",
			["icon"] = "Interface\\Icons\\INV_Potion_100",
			["item"] = 20748,
		},
		[25129] = {
			["name"] = "Brilliant Wizard Oil",
			["icon"] = "Interface\\Icons\\INV_Potion_105",
			["item"] = 20749,
		},
		[25078] = {
			["name"] = "Enchant Gloves - Fire Power",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[25079] = {
			["name"] = "Enchant Gloves - Healing Power",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[25080] = {
			["name"] = "Enchant Gloves - Superior Agility",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[25081] = {
			["name"] = "Enchant Cloak - Greater Fire Resistance",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[25082] = {
			["name"] = "Enchant Cloak - Greater Nature Resistance",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[25083] = {
			["name"] = "Enchant Cloak - Stealth",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[25084] = {
			["name"] = "Enchant Cloak - Subtlety",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[25086] = {
			["name"] = "Enchant Cloak - Dodge",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[25072] = {
			["name"] = "Enchant Gloves - Threat",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[25073] = {
			["name"] = "Enchant Gloves - Shadow Power",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[25074] = {
			["name"] = "Enchant Gloves - Frost Power",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[22749] = {
			["name"] = "Enchant Weapon - Spell Power",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
		[22750] = {
			["name"] = "Enchant Weapon - Healing Power",
			["icon"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
		},
	},
	["craftspells"] = {
		[0000] = {
			["name"] = "TemplateName",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\TemplateIcon",
			["text"] = "",
			["craftItem"] = 0000,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {0000},
			},
		},
		[6510] = {
			["name"] = "Rogue: Blinding Powder",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_ammo_gunpowder_01",
			["text"] = "Create the reagent for the Blind ability.",
			["craftItem"] = 5530,
			["craftQuantityMin"] = 3,
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {3818},
			},
		},
		[8681] = {
			["name"] = "Rogue: Instant Poison",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\ability_poisons",
			["text"] = "Coats a weapon with poison that lasts for 30 minutes.\nEach strike has a 20% chance of poisoning the enemy which instantly inflicts 19 to 25 Nature damage. 40 charges.",
			["craftItem"] = 6947,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2928},
				[2] = {3371},
			},
		},
		[8687] = {
			["name"] = "Rogue: Instant Poison II",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\ability_poisons",
			["text"] = "Coats a weapon with poison that lasts for 30 minutes.\nEach strike has a 20% chance of poisoning the enemy which instantly inflicts 30 to 38 Nature damage. 55 charges.",
			["craftItem"] = 6949,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2928, 3},
				[2] = {3372},
			},
		},
		[8691] = {
			["name"] = "Rogue: Instant Poison III",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\ability_poisons",
			["text"] = "Coats a weapon with poison that lasts for 30 minutes.\nEach strike has a 20% chance of poisoning the enemy which instantly inflicts 44 to 56 Nature damage. 70 charges.",
			["craftItem"] = 6950,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {8924},
				[2] = {3372},
			},
		},
		[11341] = {
			["name"] = "Rogue: Instant Poison IV",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\ability_poisons",
			["text"] = "Coats a weapon with poison that lasts for 30 minutes.\nEach strike has a 20% chance of poisoning the enemy which instantly inflicts 67 to 85 Nature damage. 85 charges.",
			["craftItem"] = 8926,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {8924, 2},
				[2] = {8925},
			},
		},
		[11342] = {
			["name"] = "Rogue: Instant Poison V",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\ability_poisons",
			["text"] = "Coats a weapon with poison that lasts for 30 minutes.\nEach strike has a 20% chance of poisoning the enemy which instantly inflicts 92 to 118 Nature damage. 100 charges.",
			["craftItem"] = 8927,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {8924, 3},
				[2] = {8925},
			},
		},
		[11343] = {
			["name"] = "Rogue: Instant Poison VI",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\ability_poisons",
			["text"] = "Coats a weapon with poison that lasts for 30 minutes.\nEach strike has a 20% chance of poisoning the enemy which instantly inflicts 112 to 148 Nature damage. 115 charges.",
			["craftItem"] = 8928,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {8924, 4},
				[2] = {8925},
			},
		},
		[3420] = {
			["name"] = "Rogue: Crippling Poison",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\ability_poisonsting",
			["text"] = "Coats a weapon with poison that lasts for 30 minutes.\nEach strike has a 30% chance of poisoning the enemy, slowing their movement speed by 50% for 12 sec.",
			["craftItem"] = 3775,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2930},
				[2] = {3371},
			},
		},
		[3421] = {
			["name"] = "Rogue: Crippling Poison II",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_potion_19",
			["text"] = "Coats a weapon with poison that lasts for 30 minutes.\nEach strike has a 30% chance of poisoning the enemy, slowing their movement speed by 70% for 12 sec.",
			["craftItem"] = 3776,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {8923, 3},
				[2] = {8925},
			},
		},
		[5763] = {
			["name"] = "Rogue: Mind-numbing Poison",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\spell_nature_nullifydisease",
			["text"] = "Coats a weapon with poison that lasts for 30 minutes.\nEach strike has a 20% chance of poisoning the enemy, increasing their casting time by 40% for 10 sec. 50 charges.",
			["craftItem"] = 5237,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2928},
				[2] = {2930},
				[3] = {3371},
			},
		},
		[8694] = {
			["name"] = "Rogue: Mind-numbing Poison II",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\spell_nature_nullifydisease",
			["text"] = "Coats a weapon with poison that lasts for 30 minutes.\nEach strike has a 20% chance of poisoning the enemy, increasing their casting time by 50% for 12 sec. 75 charges.",
			["craftItem"] = 6951,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2928, 4},
				[2] = {2930, 4},
				[3] = {3372},
			},
		},
		[11400] = {
			["name"] = "Rogue: Mind-numbing Poison III",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\spell_nature_nullifydisease",
			["text"] = "Coats a weapon with poison that lasts for 30 minutes.\nEach strike has a 20% chance of poisoning the enemy, increasing their casting time by 60% for 14 sec. 100 charges.",
			["craftItem"] = 9186,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {8924, 2},
				[2] = {8923, 2},
				[3] = {8925},
			},
		},
		[2835] = {
			["name"] = "Rogue: Deadly Poison",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\ability_rogue_dualweild",
			["text"] = "Coats a weapon with poison that lasts for 30 minutes.\nEach strike has a 30% chance of poisoning the enemy for 36 Nature damage over 12 sec. Stacks up to 5 times on a single target. 60 charges.",
			["craftItem"] = 2892,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {5173},
				[2] = {3372},
			},
		},
		[2837] = {
			["name"] = "Rogue: Deadly Poison II",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\ability_rogue_dualweild",
			["text"] = "Coats a weapon with poison that lasts for 30 minutes.\nEach strike has a 30% chance of poisoning the enemy for 52 Nature damage over 12 sec. Stacks up to 5 times on a single target. 75 charges.",
			["craftItem"] = 2893,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {5173, 2},
				[2] = {3372},
			},
		},
		[11357] = {
			["name"] = "Rogue: Deadly Poison III",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\ability_rogue_dualweild",
			["text"] = "Coats a weapon with poison that lasts for 30 minutes.\nEach strike has a 30% chance of poisoning the enemy for 80 Nature damage over 12 sec. Stacks up to 5 times on a single target. 90 charges.",
			["craftItem"] = 8984,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {5173, 3},
				[2] = {8925},
			},
		},
		[11358] = {
			["name"] = "Rogue: Deadly Poison IV",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\ability_rogue_dualweild",
			["text"] = "Coats a weapon with poison that lasts for 30 minutes.\nEach strike has a 30% chance of poisoning the enemy for 108 Nature damage over 12 sec. Stacks up to 5 times on a single target. 105 charges.",
			["craftItem"] = 8985,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {5173, 5},
				[2] = {8925},
			},
		},
		[25347] = {
			["name"] = "Rogue: Deadly Poison V",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\ability_rogue_dualweild",
			["text"] = "Coats a weapon with poison that lasts for 30 minutes.\nEach strike has a 30% chance of poisoning the enemy for 136 Nature damage over 12 sec. Stacks up to 5 times on a single target. 120 charges.",
			["craftItem"] = 20844,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {5173, 7},
				[2] = {8925},
			},
		},
		[13220] = {
			["name"] = "Rogue: Wound Poison",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\ability_poisonsting",
			["text"] = "Coats a weapon with poison that lasts for 30 minutes.\nEach strike has a 30% chance of poisoning the enemy, reducing all healing effects used on them by 55 for 15 sec. Stacks up to 5 times on a single target. 60 charges.",
			["craftItem"] = 10918,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2930},
				[2] = {5173},
				[2] = {3372},
			},
		},
		[13228] = {
			["name"] = "Rogue: Wound Poison II",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\ability_poisonsting",
			["text"] = "Coats a weapon with poison that lasts for 30 minutes.\nEach strike has a 30% chance of poisoning the enemy, reducing all healing effects used on them by 75 for 15 sec. Stacks up to 5 times on a single target. 75 charges.",
			["craftItem"] = 10920,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2930},
				[2] = {5173, 2},
				[2] = {3372},
			},
		},
		[13229] = {
			["name"] = "Rogue: Wound Poison III",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\ability_poisonsting",
			["text"] = "Coats a weapon with poison that lasts for 30 minutes.\nEach strike has a 30% chance of poisoning the enemy, reducing all healing effects used on them by 105 for 15 sec. Stacks up to 5 times on a single target. 90 charges.",
			["craftItem"] = 10921,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {8923},
				[2] = {5173, 2},
				[3] = {8925},
			},
		},
		[13230] = {
			["name"] = "Rogue: Wound Poison IV",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\ability_poisonsting",
			["text"] = "Coats a weapon with poison that lasts for 30 minutes.\nEach strike has a 30% chance of poisoning the enemy, reducing all healing effects used on them by 135 for 15 sec. Stacks up to 5 times on a single target. 105 charges.",
			["craftItem"] = 10922,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {8923, 2},
				[2] = {5173, 2},
				[3] = {8925},
			},
		},
		[3275] = {
			["name"] = "First Aid: Linen Bandage",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_bandage_15",
			["text"] = "",
			["craftItem"] = 1251,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2589},
			},
		},
		[3276] = {
			["name"] = "First Aid: Heavy Linen Bandage",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_bandage_18",
			["text"] = "",
			["craftItem"] = 2581,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2589, 2},
			},
		},
		[7934] = {
			["name"] = "First Aid: Anti-Venom",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_slime_01",
			["text"] = "Creates 3 Vials of Anti-Venom.",
			["craftItem"] = 6452,
			["craftQuantityMin"] = 3,
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {1475},
			},
		},
		[3277] = {
			["name"] = "First Aid: Wool Bandage",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_bandage_14",
			["text"] = "",
			["craftItem"] = 3530,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2592},
			},
		},
		[3278] = {
			["name"] = "First Aid: Heavy Wool Bandage",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_bandage_17",
			["text"] = "",
			["craftItem"] = 3531,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2592, 2},
			},
		},
		[7935] = {
			["name"] = "First Aid: Strong Anti-Venom",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_slime_01",
			["text"] = "Creates 3 Vials of Strong Anti-Venom.",
			["craftItem"] = 6453,
			["craftQuantityMin"] = 3,
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {1288},
			},
		},
		[7928] = {
			["name"] = "First Aid: Silk Bandage",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_bandage_01",
			["text"] = "",
			["craftItem"] = 6450,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {4306},
			},
		},
		[7929] = {
			["name"] = "First Aid: Heavy Silk Bandage",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_bandage_02",
			["text"] = "",
			["craftItem"] = 6451,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {4306, 2},
			},
		},
		[10840] = {
			["name"] = "First Aid: Mageweave Bandage",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_bandage_19",
			["text"] = "",
			["craftItem"] = 8544,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {4338},
			},
		},
		[10841] = {
			["name"] = "First Aid: Heavy Mageweave Bandage",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_bandage_20",
			["text"] = "",
			["craftItem"] = 8545,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {4338, 2},
			},
		},
		[18629] = {
			["name"] = "First Aid: Runecloth Bandage",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_bandage_11",
			["text"] = "",
			["craftItem"] = 14529,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {14047},
			},
		},
		[18630] = {
			["name"] = "First Aid: Heavy Runecloth Bandage",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_bandage_12",
			["text"] = "",
			["craftItem"] = 14530,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {14047, 2},
			},
		},
		[23787] = {
			["name"] = "First Aid: Powerful Anti-Venom",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_drink_14",
			["text"] = "Creates a Vial of Powerful Anti-Venom.",
			["craftItem"] = 19440,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {19441},
			},
		},
		[818] = {
			["name"] = "Basic Campfire",
			["requires"] = "",
			["tools"] = {4471},
			["castTime"] = 10,
			["icon"] = "Interface\\Icons\\spell_fire_fire",
			["text"] = "Builds a campfire that increases the spirits of those nearby by 4 and allows cooking.",
			["craftItem"] = "",
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {4470},
			},
		},
		[7752] = {
			["name"] = "Cooking: Slitherskin Mackerel",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_fish_24",
			["text"] = "",
			["craftItem"] = 787,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {6303},
			},
		},
		[2538] = {
			["name"] = "Cooking: Charred Wolf Meat",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_18",
			["text"] = "",
			["craftItem"] = 2679,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2672},
			},
		},
		[7751] = {
			["name"] = "Cooking: Brilliant Smallfish",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_fish_07",
			["text"] = "",
			["craftItem"] = 6290,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {6291},
			},
		},
		[15935] = {
			["name"] = "Cooking: Crispy Bat Wing",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_46",
			["text"] = "",
			["craftItem"] = 12224,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {12223},
				[2] = {2678},
			},
		},
		[21143] = {
			["name"] = "Cooking: Gingerbread Cookie",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_62",
			["text"] = "",
			["craftItem"] = 17197,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {6889},
				[2] = {17194},
			},
		},
		[8604] = {
			["name"] = "Cooking: Herb Baked Egg",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_egg_03",
			["text"] = "",
			["craftItem"] = 6888,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {6889},
				[2] = {2678},
			},
		},
		[2540] = {
			["name"] = "Cooking: Roasted Boar Meat",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_18",
			["text"] = "",
			["craftItem"] = 2681,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {769},
			},
		},
		[6412] = {
			["name"] = "Cooking: Kaldorei Spider Kabob",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_68",
			["text"] = "",
			["craftItem"] = 5472,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {5465},
			},
		},
		[2539] = {
			["name"] = "Cooking: Spiced Wolf Meat",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_65",
			["text"] = "",
			["craftItem"] = 2680,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2672},
				[2] = {2678},
			},
		},
		[6413] = {
			["name"] = "Cooking: Scorpid Surprise",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_10",
			["text"] = "",
			["craftItem"] = 5473,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {5466},
			},
		},
		[2795] = {
			["name"] = "Cooking: Beer Basted Boar Ribs",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_48",
			["text"] = "",
			["craftItem"] = 2888,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2886},
				[2] = {2894},
			},
		},
		[21144] = {
			["name"] = "Cooking: Egg Nog",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_drink_04",
			["text"] = "",
			["craftItem"] = 17198,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {6889},
				[2] = {1179},
				[3] = {17196},
				[4] = {17194},
			},
		},
		[6414] = {
			["name"] = "Cooking: Roasted Kodo Meat",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_60",
			["text"] = "",
			["craftItem"] = 5474,
			["craftQuantityMin"] = 2,
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {5467},
				[2] = {2678},
			},
		},
		[8607] = {
			["name"] = "Cooking: Roasted Kodo Meat",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_13",
			["text"] = "",
			["craftItem"] = 6890,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {3173},
			},
		},
		[6499] = {
			["name"] = "Cooking: Boiled Clams",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_shell_02",
			["text"] = "",
			["craftItem"] = 5525,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {5503},
				[2] = {159},
			},
		},
		[2541] = {
			["name"] = "Cooking: Coyote Steak",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_65",
			["text"] = "",
			["craftItem"] = 2684,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2673},
			},
		},
		[6415] = {
			["name"] = "Cooking: Fillet of Frenzy",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_fish_05",
			["text"] = "",
			["craftItem"] = 5476,
			["craftQuantityMin"] = 2,
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {5468},
				[2] = {2678},
			},
		},
		[2542] = {
			["name"] = "Cooking: Goretusk Liver Pie",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_10",
			["text"] = "",
			["craftItem"] = 724,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {723},
				[2] = {2678},
			},
		},
		[7754] = {
			["name"] = "Cooking: Loch Frenzy Delight",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_potion_01",
			["text"] = "",
			["craftItem"] = 6316,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {6317},
				[2] = {2678},
			},
		},
		[7753] = {
			["name"] = "Cooking: Longjaw Mud Snapper",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_fish_32",
			["text"] = "",
			["craftItem"] = 4592,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {6289},
			},
		},
		[7827] = {
			["name"] = "Cooking: Rainbow Fin Albacore",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_fish_27",
			["text"] = "",
			["craftItem"] = 5095,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {6361},
			},
		},
		[6416] = {
			["name"] = "Cooking: Strider Stew",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_bowl_01",
			["text"] = "",
			["craftItem"] = 5477,
			["craftQuantityMin"] = 2,
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {5469},
				[2] = {4536},
			},
		},
		[3371] = {
			["name"] = "Cooking: Blood Sausage",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_49",
			["text"] = "",
			["craftItem"] = 3220,
			["craftQuantityMin"] = 2,
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {3173},
				[2] = {3172},
				[3] = {3174},
			},
		},
		[9513] = {
			["name"] = "Cooking: Thistle Tea",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_drink_milk_05",
			["text"] = "",
			["craftItem"] = 7676,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2452},
				[2] = {159},
			},
		},
		[2544] = {
			["name"] = "Cooking: Crab Cake",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_08",
			["text"] = "",
			["craftItem"] = 2683,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2674},
				[2] = {2678},
			},
		},
		[2543] = {
			["name"] = "Cooking: Westfall Stew",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_bowl_01",
			["text"] = "",
			["craftItem"] = 733,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {729},
				[2] = {730},
				[3] = {731},
			},
		},
		[3370] = {
			["name"] = "Cooking: Crocolisk Steak",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_47",
			["text"] = "",
			["craftItem"] = 3662,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2924},
				[2] = {2678},
			},
		},
		[2546] = {
			["name"] = "Cooking: Dry Pork Ribs",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_48",
			["text"] = "",
			["craftItem"] = 2687,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2677},
				[2] = {2678},
			},
		},
		[25704] = {
			["name"] = "Cooking: Smoked Sagefish",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_fish_20",
			["text"] = "",
			["craftItem"] = 21072,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {21071},
				[2] = {2678},
			},
		},
		[2545] = {
			["name"] = "Cooking: Cooked Crab Claw",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_birdbeck_02",
			["text"] = "",
			["craftItem"] = 2682,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2675},
				[2] = {2678},
			},
		},
		[8238] = {
			["name"] = "Cooking: Savory Deviate Delight",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_monsterhead_04",
			["text"] = "",
			["craftItem"] = 6657,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {6522},
				[2] = {2678},
			},
		},
		[2963] = {
			["name"] = "Tailoring: Bolt of Linen Cloth",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_fabric_linen_02",
			["text"] = "",
			["craftItem"] = 2996,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2589, 2},
			},
		},
		[3915] = {
			["name"] = "Tailoring: Brown Linen Shirt",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 5.125,
			["icon"] = "Interface\\Icons\\inv_shirt_02",
			["text"] = "",
			["craftItem"] = 4344,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2996},
				[2] = {2320},
			},
		},
		[2387] = {
			["name"] = "Tailoring: Linen Cloak",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 5.125,
			["icon"] = "Interface\\Icons\\inv_misc_cape_14",
			["text"] = "",
			["craftItem"] = 2570,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2996},
				[2] = {2320},
			},
		},
		[12044] = {
			["name"] = "Tailoring: Simple Linen Pants",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 5.125,
			["icon"] = "Interface\\Icons\\inv_pants_11",
			["text"] = "",
			["craftItem"] = 10045,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2996},
				[2] = {2320},
			},
		},
		[2393] = {
			["name"] = "Tailoring: White Linen Shirt",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 5.125,
			["icon"] = "Interface\\Icons\\inv_shirt_white_01",
			["text"] = "",
			["craftItem"] = 2576,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2996},
				[2] = {2320},
				[3] = {2324},
			},
		},
		[2385] = {
			["name"] = "Tailoring: Brown Linen Vest",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 5.125,
			["icon"] = "Interface\\Icons\\inv_shirt_05",
			["text"] = "",
			["craftItem"] = 2568,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2996},
				[2] = {2320},
			},
		},
		[8776] = {
			["name"] = "Tailoring: Linen Belt",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 5.125,
			["icon"] = "Interface\\Icons\\inv_belt_05",
			["text"] = "",
			["craftItem"] = 7026,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2996},
				[2] = {2320},
			},
		},
		[12045] = {
			["name"] = "Tailoring: Simple Linen Boots",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 5.125,
			["icon"] = "Interface\\Icons\\inv_boots_05",
			["text"] = "",
			["craftItem"] = 10046,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2996, 2},
				[2] = {2318},
				[3] = {2320},
			},
		},
		[7623] = {
			["name"] = "Tailoring: Brown Linen Robe",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 8,
			["icon"] = "Interface\\Icons\\inv_chest_cloth_21",
			["text"] = "",
			["craftItem"] = 6238,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2996, 3},
				[2] = {2320},
			},
		},
		[7624] = {
			["name"] = "Tailoring: White Linen Robe",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 8,
			["icon"] = "Interface\\Icons\\inv_chest_cloth_04",
			["text"] = "",
			["craftItem"] = 6241,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2996, 3},
				[2] = {2320},
				[3] = {2324},
			},
		},
		[3914] = {
			["name"] = "Tailoring: Brown Linen Pants",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 5.125,
			["icon"] = "Interface\\Icons\\inv_pants_06",
			["text"] = "",
			["craftItem"] = 4343,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2996, 2},
				[2] = {2320},
			},
		},
		[3840] = {
			["name"] = "Tailoring: Heavy Linen Gloves",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 5.125,
			["icon"] = "Interface\\Icons\\inv_gauntlets_05",
			["text"] = "",
			["craftItem"] = 4307,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2996, 2},
				[2] = {2320},
			},
		},
		[2389] = {
			["name"] = "Tailoring: Red Linen Robe",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 8,
			["icon"] = "Interface\\Icons\\inv_chest_cloth_18",
			["text"] = "",
			["craftItem"] = 2572,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2996, 2},
				[2] = {2320, 2},
				[3] = {2604, 2},
			},
		},
		[2394] = {
			["name"] = "Tailoring: Blue Linen Shirt",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 5.125,
			["icon"] = "Interface\\Icons\\inv_shirt_blue_01",
			["text"] = "",
			["craftItem"] = 2577,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2996, 2},
				[2] = {2320},
				[3] = {6260},
			},
		},
		[2392] = {
			["name"] = "Tailoring: Red Linen Shirt",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 5.125,
			["icon"] = "Interface\\Icons\\inv_shirt_red_01",
			["text"] = "",
			["craftItem"] = 2575,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2996, 2},
				[2] = {2320},
				[3] = {2604},
			},
		},
		[8465] = {
			["name"] = "Tailoring: Simple Dress",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 5.125,
			["icon"] = "Interface\\Icons\\inv_shirt_12",
			["text"] = "",
			["craftItem"] = 6786,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2996, 2},
				[2] = {2320},
				[3] = {6260},
				[4] = {2324},
			},
		},
		[3755] = {
			["name"] = "Tailoring: Linen Bag",
			["requires"] = "",
			["tools"] = "",
			["castTime"] = 8,
			["icon"] = "Interface\\Icons\\inv_misc_bag_01",
			["text"] = "",
			["craftItem"] = 4238,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2996, 3},
				[2] = {2320, 3},
			},
		},
		[6501] = {
			["name"] = "Cooking: Clam Chowder",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_potion_01",
			["text"] = "",
			["craftItem"] = 5526,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {5503},
				[2] = {1179},
				[3] = {2678},
			},
		},
		[6417] = {
			["name"] = "Cooking: Dig Rat Stew",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_bowl_01",
			["text"] = "",
			["craftItem"] = 5478,
			["craftQuantityMin"] = 2,
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {5051},
			},
		},
		[3372] = {
			["name"] = "Cooking: Murloc Fin Soup",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_bowl_01",
			["text"] = "",
			["craftItem"] = 3663,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {1468, 2},
				[2] = {2692},
			},
		},
		[2547] = {
			["name"] = "Cooking: Redridge Goulash",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_bowl_01",
			["text"] = "",
			["craftItem"] = 1082,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {1081},
				[2] = {1080},
			},
		},
		[7755] = {
			["name"] = "Cooking: Bristle Whisker Catfish",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_fish_30",
			["text"] = "",
			["craftItem"] = 4593,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {6308},
			},
		},
		[6418] = {
			["name"] = "Cooking: Crispy Lizard Tail",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_17",
			["text"] = "",
			["craftItem"] = 5479,
			["craftQuantityMin"] = 2,
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {5470},
				[2] = {2692},
			},
		},
		[2549] = {
			["name"] = "Cooking: Seasoned Wolf Kabob",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_16",
			["text"] = "",
			["craftItem"] = 1017,
			["craftQuantityMin"] = 3,
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {1015, 2},
				[2] = {2665},
			},
		},
		[2548] = {
			["name"] = "Cooking: Succulent Pork Ribs",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_16",
			["text"] = "",
			["craftItem"] = 2685,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2677},
				[2] = {2692},
			},
		},
		[3397] = {
			["name"] = "Cooking: Big Bear Steak",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_47",
			["text"] = "",
			["craftItem"] = 3726,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {3730},
				[2] = {2692},
			},
		},
		[3377] = {
			["name"] = "Cooking: Gooey Spider Cake",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_10",
			["text"] = "",
			["craftItem"] = 3666,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {2251, 2},
				[2] = {2692},
			},
		},
		[6419] = {
			["name"] = "Cooking: Lean Venison",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_72",
			["text"] = "",
			["craftItem"] = 5480,
			["craftQuantityMin"] = 2,
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {5471},
				[2] = {2678, 4},
			},
		},
		[3373] = {
			["name"] = "Cooking: Crocolisk Gumbo",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_bowl_01",
			["text"] = "",
			["craftItem"] = 3664,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {3667},
				[2] = {2692},
			},
		},
		[6500] = {
			["name"] = "Cooking: Goblin Deviled Clams",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_shell_01",
			["text"] = "",
			["craftItem"] = 5527,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {5504},
				[2] = {2692},
			},
		},
		[15853] = {
			["name"] = "Cooking: Lean Wolf Steak",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_47",
			["text"] = "",
			["craftItem"] = 12209,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {1015},
				[2] = {2678},
			},
		},
		[3398] = {
			["name"] = "Cooking: Hot Lion Chops",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_18",
			["text"] = "",
			["craftItem"] = 3727,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {3731},
				[2] = {2692},
			},
		},
		[3376] = {
			["name"] = "Cooking: Curiously Tasty Omelet",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_egg_04",
			["text"] = "",
			["craftItem"] = 3665,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {3685},
				[2] = {2692},
			},
		},
		[24418] = {
			["name"] = "Cooking: Heavy Crocolisk Stew",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_64",
			["text"] = "",
			["craftItem"] = 20074,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {3667, 2},
				[2] = {3713},
			},
		},
		[3399] = {
			["name"] = "Cooking: Tasty Lion Steak",
			["requires"] = AL["Cooking Fire"],
			["tools"] = "",
			["castTime"] = 3,
			["icon"] = "Interface\\Icons\\inv_misc_food_14",
			["text"] = "",
			["craftItem"] = 3728,
			["craftQuantityMin"] = "",
			["craftQuantityMax"] = "",
			["reagents"] = {
				[1] = {3731, 2},
				[2] = {3713},
			},
		},
	},
}
